### ISSUE TITLE
my great thing

### ISSUE THREAD

**Issue by karlbenedict** [imls-dmt/resources-workflow#1]
It's great but ...

OK - fine

Done

**Comment by karlbenedict** [comment]
So what's up with the discipline field???

@njhoebel

**Comment by njhoebel** [comment]
Who needs discipline anyway?

 

 

 

 <https://kmotifs.com/> _LOGOhiResTRANSPARENT_4800pxRGB

 

Nancy J. Hoebelheinrich

Information Analyst/Principal

nhoebel@kmotifs.com

San Mateo, CA  94401

(v) 650-302-4493

(f) 650-745-3333

**Comment by karlbenedict** [comment]
Another comment
