### ISSUE TITLE
Biology Metadata Standards

### ISSUE THREAD

**Issue by jwikle** [imls-dmt/resources-workflow#10]
Information about registered data management training resource

- [ ] Date resource added: 08/27/2018
- [ ] Registered by: jwikle
- [ ] Clearinghouse URL: http://dmtclearinghouse.esipfed.org/node/10181

**Comment by njhoebel** [comment]
This is another static web page that would more properly (per our selection criteria) be included in a course as a reference.  So, will not publish, but will pass on to DataONE for their Best Practices collection, if they think it's appropriate.
