### ISSUE TITLE
Introduction to Research Data Management

### ISSUE THREAD

**Issue by jwikle** [imls-dmt/resources-workflow#106]
Information about registered data management training resource

- [ ] Date resource added: 10/01/2018
- [ ] Registered by: jwikle
- [ ] Clearinghouse URL: http://dmtclearinghouse.esipfed.org/node/10241 

Tracking: @karlbenedict @njhoebel

**Comment by njhoebel** [comment]
The quality of this presentation is not very good;  there are comments and questions from the audience, apparently, that cannot be heard and are not repeated by the presenter before answering.  The information is not particularly unique, and is somewhat Texas State U specific.  
Will not publish and remove from DMTC.
