### ISSUE TITLE
Data Management Plans for the Social Sciences

### ISSUE THREAD

**Issue by jwikle** [imls-dmt/resources-workflow#109]
Information about registered data management training resource

- [ ] Date resource added: 10/08/2018
- [ ] Registered by: jwikle
- [ ] Clearinghouse URL: http://dmtclearinghouse.esipfed.org/node/10245

Tracking: @karlbenedict @njhoebel

**Comment by njhoebel** [comment]
Static web page, most of the information coming from other sources;  no downloadable educational resources.  Does not fit selection criteria.
