### ISSUE TITLE
Data Services: Introduction to Data Management

### ISSUE THREAD

**Issue by jwikle** [imls-dmt/resources-workflow#112]
Information about registered data management training resource

- [ ] Date resource added: 10/22/2018
- [ ] Registered by: jwikle
- [ ] Clearinghouse URL: http://dmtclearinghouse.esipfed.org/node/10198

Tracking: @karlbenedict @njhoebel

**Comment by njhoebel** [comment]
No longer available.  Remove from DMTC.
