### ISSUE TITLE
Database Administration Courses

### ISSUE THREAD

**Issue by jwikle** [imls-dmt/resources-workflow#118]
Information about registered data management training resource

- [ ] Date resource added: 10/29/2018
- [ ] Registered by: jwikle
- [ ] Clearinghouse URL: http://dmtclearinghouse.esipfed.org/node/10254

Tracking: @karlbenedict @njhoebel

**Comment by njhoebel** [comment]
Discovered this resource is no longer available.  Remove from DMTC.
