### ISSUE TITLE
Introduction to Python GIS for Data Science

### ISSUE THREAD

**Issue by jwikle** [imls-dmt/resources-workflow#12]
Information about registered data management training resource

- [ ] Date resource added: 08/27/2018
- [ ] Registered by: jwikle
- [ ] Clearinghouse URL:  http://dmtclearinghouse.esipfed.org/node/10171

**Comment by njhoebel** [comment]
1.  Added General Assembly as both Authoring organization (associated with person presenting), and publisher.  
2.  Changed the learning resource type to "lesson" rather than course.
Should be a useful resource.
