### ISSUE TITLE
Best Practice in Open Research

### ISSUE THREAD

**Issue by jwikle** [imls-dmt/resources-workflow#127]
Information about registered data management training resource

- [ ] Date resource added: 11/12/2018
- [ ] Registered by: jwikle
- [ ] Clearinghouse URL: http://dmtclearinghouse.esipfed.org/node/10267

Tracking: @karlbenedict @njhoebel

**Comment by njhoebel** [comment]
This item was already in the DMTC, so is a dupe record.  Remove from DMTC.
