### ISSUE TITLE
ScienceBase as a Platform for Data Release

### ISSUE THREAD

**Issue by jwikle** [imls-dmt/resources-workflow#129]
Information about registered data management training resource

- [ ] Date resource added: 11/15/2018
- [ ] Registered by: jwikle
- [ ] Clearinghouse URL: http://dmtclearinghouse.esipfed.org/node/10269

Tracking: @karlbenedict @njhoebel

**Comment by raisaionin** [comment]
added:

keywords: metadata
framework: USGS Science Support Network
purpose: instruction
time to complete: up to 1 hour
media type: presentation
learning resource type: learning activity

**Comment by njhoebel** [comment]
Looks good.  Just added U.S. Geological Survey to Contact Information.
