### ISSUE TITLE
Introduction to Python GIS for Data Science

### ISSUE THREAD

**Issue by jwikle** [imls-dmt/resources-workflow#13]
Information about registered data management training resource

- [ ] Date resource added: 08/27/2018
- [ ] Registered by: jwikle
- [ ] Clearinghouse URL: http://dmtclearinghouse.esipfed.org/node/10171

**Comment by raisaionin** [comment]
Seems like this record is a duplicate. This same record is registered as Issue #12, https://github.com/imls-dmt/resources-workflow/issues/12
and Issue 12 is already closed.
