### ISSUE TITLE
SQL for Librarians

### ISSUE THREAD

**Issue by jwikle** [imls-dmt/resources-workflow#131]
Information about registered data management training resource

- [ ] Date resource added: 11/15/2018
- [ ] Registered by: jwikle
- [ ] Clearinghouse URL: http://dmtclearinghouse.esipfed.org/node/10271

Tracking: @karlbenedict @njhoebel

**Comment by njhoebel** [comment]
1.  Couldn't find author names in the resource.

**Comment by njhoebel** [comment]
From Raisa:  when registered an issue erroneously on clearinghouse-code thread:
1.  Uncertain about Authoring Person(s) Name: Elaine Wong (3440), Janice Chan (3439)
Unable to find these in the original resource pages: https://librarycarpentry.org/lc-sql/
2.  I put "Professional development" for Purpose. It actually can fit both Instruction and Professional development, but seems more like development to me.
From NH:  needs to be reviewed by me.

**Comment by njhoebel** [comment]
From NH:  upon review
1.  Deleted author names as there was no evidence of those names;  kept authoring organization as Library Carpentries.
2.  Added license information;  found on the main repo site for this record.
3.  Changed keyword "SQL" to be "Structured Query Language (SQL)".
4.  Changed Purpose to "Instruction".
Move to Publish.  Published in DMTC.
