### ISSUE TITLE
Python Intro for Libraries

### ISSUE THREAD

**Issue by jwikle** [imls-dmt/resources-workflow#132]
Information about registered data management training resource

- [ ] Date resource added: 11/15/2018
- [ ] Registered by: jwikle
- [ ] Clearinghouse URL: http://dmtclearinghouse.esipfed.org/node/10272

Tracking: @karlbenedict @njhoebel

**Comment by raisaionin** [comment]
added keywords: library science
added license: CC BY 4.0 license
added version:  9.5.2.
added purpose: instruction
added time to complete: more than 1 hour, less than 1 day
added media type: interactive resource
added learning resource type:  lesson

**Comment by raisaionin** [comment]
added citation : Software Carpentry: Plotting and Programming in Python.
http://github.com/swcarpentry/python-novice-plotting,
2016.

**Comment by njhoebel** [comment]
This lesson is currently under design and does not have a DOI, so we'll have to keep track of it to add the DOI when it is officially published from LIbrary Carpentry POV.  In the meantime, I have:
1.  Added a note to the effect that the lesson is under design and make undergo substantial changes.
2.  Taken out the author and contact names as I couldn't find any verification of those names as authors (please let me know if you found them, Raisa).
3.  Added Data professional and Data supporter to the target audience field.
4.  Changed the citation to what was suggested on the github cite.  The URL on that citation goes to the front page of the github site.
Moved to Publish.
