### ISSUE TITLE
Introduction to GRASS GIS

### ISSUE THREAD

**Issue by jwikle** [imls-dmt/resources-workflow#133]
Information about registered data management training resource

- [ ] Date resource added: 11/15/2018
- [ ] Registered by: jwikle
- [ ] Clearinghouse URL: http://dmtclearinghouse.esipfed.org/node/10273

Tracking: @karlbenedict @njhoebel

**Comment by raisaionin** [comment]
added:

License: CC 4.0
time to complete: more than 1 day, but less then a week

**Comment by njhoebel** [comment]
1.  Added more information about the TOC to the Description field.
2.  Added Data analysis, Data modeling, and Network Analysis to the Keyword field.
3.  Added Physical Sciences & Mathematics for Earth Science and Environmental Science to the Subject Discipline field.
4.  Changed the Media type to Interactive Resource.
Moved to Publish
