### ISSUE TITLE
Metadata for Data Management: A Tutorial

### ISSUE THREAD

**Issue by jwikle** [imls-dmt/resources-workflow#135]
Information about registered data management training resource

- [ ] Date resource added: 11/19/2018
- [ ] Registered by: jwikle
- [ ] Clearinghouse URL: http://dmtclearinghouse.esipfed.org/node/10277

Tracking: @karlbenedict @njhoebel

**Comment by njhoebel** [comment]
Not unique or particularly noteworthy as an example and is a static series of webpages not updated since 2016.  Doesn't meet Selection Criteria.
Remove from DMTC.
