### ISSUE TITLE
Research Data Management Guide

### ISSUE THREAD

**Issue by jwikle** [imls-dmt/resources-workflow#137]
Information about registered data management training resource

- [ ] Date resource added: 11/19/2018
- [ ] Registered by: jwikle
- [ ] Clearinghouse URL: http://dmtclearinghouse.esipfed.org/node/10279

Tracking: @karlbenedict @njhoebel

**Comment by njhoebel** [comment]
While this resource would not normally be included as it is another overview guide, there are some interesting and unusual features to the page including RDM good and bad examples.  These links could be very helpful for Data librarians and others who will be teaching / coaching researchers and students on RDM.  I have changed the description to point on this feature.
Moved to publish.
