### ISSUE TITLE
MIT GeoWeb

### ISSUE THREAD

**Issue by jwikle** [imls-dmt/resources-workflow#141]
Information about registered data management training resource

- [ ] Date resource added: 12/03/2018
- [ ] Registered by: jwikle
- [ ] Clearinghouse URL: http://dmtclearinghouse.esipfed.org/node/10289

Tracking: @karlbenedict @njhoebel

**Comment by njhoebel** [comment]
Not an educational resource per our Selection Criteria.  Only a web portal. Remove from DMTC.
