### ISSUE TITLE
The Jupyter Notebook

### ISSUE THREAD

**Issue by jwikle** [imls-dmt/resources-workflow#146]
Information about registered data management training resource

- [ ] Date resource added: 12/10/2018
- [ ] Registered by: jwikle
- [ ] Clearinghouse URL: http://dmtclearinghouse.esipfed.org/node/10295

Tracking: @karlbenedict @njhoebel

**Comment by njhoebel** [comment]
Does not meet selection criteria.  No tutorials or other downloadable educational resources.  This is the home page for the Jupyter Notebook product.
Remove from DMTC.
