### ISSUE TITLE
Principles of Database Management

### ISSUE THREAD

**Issue by jwikle** [imls-dmt/resources-workflow#147]
Information about registered data management training resource

- [ ] Date resource added: 12/10/218
- [ ] Registered by: jwikle
- [ ] Clearinghouse URL: http://dmtclearinghouse.esipfed.org/node/10296

Tracking: @karlbenedict @njhoebel

**Comment by raisaionin** [comment]
Changes made:

Time to complete: changed from "more than 1 hour less than 1 day" to  "More than 1 week". There are 14 videos. 

Media type - put "presentation"

**Comment by njhoebel** [comment]
Added a few more keywords related to the topics covered:
Database models, database design, database management, data integration, data modeling, data quality, data governance.
Moved to publish.
