### ISSUE TITLE
Photogrammetry Workshop UNM GEM Lab

### ISSUE THREAD

**Issue by jwikle** [imls-dmt/resources-workflow#15]
Information about registered data management training resource

- [ ] Date resource added: 08/27/2018
- [ ] Registered by: jwikle
- [ ] Clearinghouse URL: http://dmtclearinghouse.esipfed.org/node/10169

**Comment by njhoebel** [comment]
Changed the form of the organization name from UNM Gem Lab to the form we've been using, i.e., "University of New Mexico Gem Lab".   Looks like a great resource.
