### ISSUE TITLE
Guide to Social Science Data Preparation and Archiving

### ISSUE THREAD

**Issue by jwikle** [imls-dmt/resources-workflow#151]
Information about registered data management training resource

- [ ] Date resource added: 1/22/2019
- [ ] Registered by: jwikle
- [ ] Clearinghouse URL: http://dmtclearinghouse.esipfed.org/node/10307

Tracking: @karlbenedict @njhoebel

**Comment by njhoebel** [comment]
The resource identified initially did not meet selection criteria as it was, essentially, a published, textual guide.  Instead, resources were identified that would be useful to an educator and researchers who wanted to learn about the resources that ICPSR provided on data curation in general, and data management more specifically.  I have kept the title of this issue the same, but the DMTC record will come up as "Teaching and Learning with ICPSR".
