### ISSUE TITLE
Visual Arts Data Toolkits

### ISSUE THREAD

**Issue by jwikle** [imls-dmt/resources-workflow#152]
Information about registered data management training resource

- [ ] Date resource added: 01/22/2019 
- [ ] Registered by: jwikle
- [ ] Clearinghouse URL: http://dmtclearinghouse.esipfed.org/node/10308

Tracking: @karlbenedict @njhoebel

**Comment by njhoebel** [comment]
Most of the links to the toolkits are not longer available (Error 404s).
