### ISSUE TITLE
Managing research data: guidance

### ISSUE THREAD

**Issue by jwikle** [imls-dmt/resources-workflow#155]
Information about registered data management training resource

- [ ] Date resource added: 01/24/2019
- [ ] Registered by: jwikle
- [ ] Clearinghouse URL: http://dmtclearinghouse.esipfed.org/node/10311

Tracking: @karlbenedict @njhoebel

**Comment by njhoebel** [comment]
This is a single web page, not a downloadable resource.  The content is quite generic.  Not suitable for inclusion.
Moved to remove from DMTC.
