### ISSUE TITLE
Data Management Guide

### ISSUE THREAD

**Issue by jwikle** [imls-dmt/resources-workflow#158]
Information about registered data management training resource

- [ ] Date resource added: 01/24/2019
- [ ] Registered by: jwikle
- [ ] Clearinghouse URL: http://dmtclearinghouse.esipfed.org/node/10314

Tracking: @karlbenedict @njhoebel

**Comment by njhoebel** [comment]
This site has useful information, but only in the form of textual guides rather than tutorials or other downloadable learning resources.  It is a fairly static web page, and does not meet our selection criteria.
