### ISSUE TITLE
Hands-on Intro to Data Cleaning with OpenRefine

### ISSUE THREAD

**Issue by jwikle** [imls-dmt/resources-workflow#16]
Information about registered data management training resource

- [ ] Date resource added: 08/27/2018
- [ ] Registered by: jwikle
- [ ] Clearinghouse URL: http://dmtclearinghouse.esipfed.org/node/10167

**Comment by njhoebel** [comment]
This looks like a good resource, but the only question I have is whether the dataset that is used is available to anyone who accesses the resource.  Perhaps you could see whether you can actually download the accompanying dataset from an open source (might be Stanford, but don't know -- the resources they have are often not available to any but the Stanford community)?  If so, then yes, should definitely be included.

**Comment by jwikle** [comment]
As it turns out, the data for this tutorial is locked behind the Stanford login page. Unfortunate, I will add the remove label.

**Comment by njhoebel** [comment]
URL in case files become open:  https://github.com/amyehodge/amyehodge.github.io/blob/master/OpenRefine/OpenRefine.md

**Comment by njhoebel** [comment]
Sent a note to author to see if she has plans to update the course and use publicly available datasets.  If so, we can keep in the DMTC until she updates (within reason!).
