### ISSUE TITLE
Data Scientist Training for Librarians

### ISSUE THREAD

**Issue by jwikle** [imls-dmt/resources-workflow#164]
Information about registered data management training resource

- [ ] Date resource added: 01/29/2019
- [ ] Registered by: jwikle
- [ ] Clearinghouse URL: http://dmtclearinghouse.esipfed.org/node/10321

Tracking: @karlbenedict @njhoebel

**Comment by njhoebel** [comment]
This resource is no longer available.  TB deleted from DMTC.
