### ISSUE TITLE
Coffee and Code: The Command Line - An Introduction

### ISSUE THREAD

**Issue by jwikle** [imls-dmt/resources-workflow#165]
Information about registered data management training resource

- [ ] Date resource added: 01/31/2019
- [ ] Registered by: jwikle
- [ ] Clearinghouse URL: http://dmtclearinghouse.esipfed.org/node/10322

Tracking: @karlbenedict @njhoebel

**Comment by raisaionin** [comment]
Changes made:
1. Date deleted - was not found
2. Keyword added, "Graphical User Interface"

**Comment by njhoebel** [comment]
Changes look good.  
Changes I made:  I did add information about the original creation date that I found on the base page for this github repository.
2.  Also added "Last updated, February 2019" in the Version field with information from the base page of this repo.
