### ISSUE TITLE
Coffee and Code: TaskJuggler

### ISSUE THREAD

**Issue by jwikle** [imls-dmt/resources-workflow#168]
Information about registered data management training resource

- [ ] Date resource added: 01/31/2019
- [ ] Registered by: jwikle
- [ ] Clearinghouse URL: http://dmtclearinghouse.esipfed.org/node/10325

Tracking: @karlbenedict @njhoebel

**Comment by njhoebel** [comment]
1. test

**Comment by njhoebel** [comment]
1.  Changed the base URL to the base page for the repository.
2.  Added keywords for Data management planning tools and research project management tools (new).
3.  Changed Media type to Interactive resource.
4.  Added target audiences for data professional and software engineer.
