### ISSUE TITLE
Coffee and Code: R & RStudio

### ISSUE THREAD

**Issue by jwikle** [imls-dmt/resources-workflow#169]
Information about registered data management training resource

- [ ] Date resource added: 01/31/2019
- [ ] Registered by: jwikle
- [ ] Clearinghouse URL: http://dmtclearinghouse.esipfed.org/node/10326

Tracking: @karlbenedict @njhoebel

**Comment by njhoebel** [comment]
1.  Changed the base URL to be the first page of the repository rather than the introduction MD page.
2.  Added keywords for data analysis and data visualization tools.
3.  Changed the Media type to Interactive Resource as there were instructions to follow & complete as part of the resource.
