### ISSUE TITLE
Coffee and Code: Natural Language Processing with Python

### ISSUE THREAD

**Issue by jwikle** [imls-dmt/resources-workflow#170]
Information about registered data management training resource

- [ ] Date resource added: 01/31/2019
- [ ] Registered by: jwikle
- [ ] Clearinghouse URL: http://dmtclearinghouse.esipfed.org/node/10327

Tracking: @karlbenedict @njhoebel

**Comment by njhoebel** [comment]
Only change I made was to add the license information (Apache 2.0) which was located in the License.txt files.  Had to add Apache to the CV list as it wasn't there yet.  
Moved to Publish
