### ISSUE TITLE
Coffee and Code: Introduction to Database Design

### ISSUE THREAD

**Issue by jwikle** [imls-dmt/resources-workflow#171]
Information about registered data management training resource

- [ ] Date resource added: 01/31/2019
- [ ] Registered by: jwikle
- [ ] Clearinghouse URL: http://dmtclearinghouse.esipfed.org/node/10328

Tracking: @karlbenedict @njhoebel

**Comment by njhoebel** [comment]
Only change to add "Introduction to" Database Design as that's what the main page said.  
Raisa Ionin added authoring name and organization too based on other Coffee & Code resources.  

Looked good;   moved to publish.
