### ISSUE TITLE
Coffee and Code: Content Platform

### ISSUE THREAD

**Issue by jwikle** [imls-dmt/resources-workflow#173]
Information about registered data management training resource

- [ ] Date resource added: 01/31/2019
- [ ] Registered by: jwikle
- [ ] Clearinghouse URL: http://dmtclearinghouse.esipfed.org/node/10330

Tracking: @karlbenedict @njhoebel

**Comment by njhoebel** [comment]
Updated by Raisa Ionin.  Looks good to me.  Moved to publish.
