### ISSUE TITLE
Polar Data Catalogue

### ISSUE THREAD

**Issue by jwikle** [imls-dmt/resources-workflow#177]
Information about registered data management training resource

- [ ] Date resource added: 02/05/2019
- [ ] Registered by: jwikle
- [ ] Clearinghouse URL: http://dmtclearinghouse.esipfed.org/node/10335

Tracking: @karlbenedict @njhoebel

**Comment by njhoebel** [comment]
Does not meet selection criteria.  A useful site, but not about RDM for polar data.
