### ISSUE TITLE
Best Practices in Data Collection and Management Workshop

### ISSUE THREAD

**Issue by jwikle** [imls-dmt/resources-workflow#178]
Information about registered data management training resource

- [ ] Date resource added: 02/05/2019
- [ ] Registered by: jwikle
- [ ] Clearinghouse URL: http://dmtclearinghouse.esipfed.org/node/10336

Tracking: @karlbenedict @njhoebel

**Comment by raisaionin** [comment]
Changed:

Added keyword: computer science
Added license: CC0, public domain
Added citation: Lake, Sherry; Denton, Andrea, 2015, "Best Practices in Data Collection and Management Workshop", https://doi.org/10.7910/DVN/29213, Harvard Dataverse, V1
Added citable locator: 10.7910/DVN/29213
Added type: DOI
added version: V.1
Corrected published broadcast date: from 02/22/2015 to 02/23/2015
Added purpose: Professional development
Added time to complete: more than 1 hour, but less than a day - there are 14 files in this dataset
Added Media type: Dataset
Added Learning Resource type: Learning Activity

**Comment by njhoebel** [comment]
All changes looked good.  Did add a little bit more information about terms of access in the description.

**Comment by raisaionin** [comment]
Thanks, Nancy!

I apologize, I have not been active in the past few months. Very busy with work. I hope to resume this work some day.

How are you doing? We are OK, working from home.How is it in CA?

Best,

Raisa.
    On Monday, April 27, 2020, 06:21:11 PM EDT, Nancy J. Hoebelheinrich <notifications@github.com> wrote:  
 
 


All changes looked good. Did add a little bit more information about terms of access in the description.
