### ISSUE TITLE
CURATE! The Digital Curator Game

### ISSUE THREAD

**Issue by jwikle** [imls-dmt/resources-workflow#179]
Information about registered data management training resource

- [ ] Date resource added: 02/07/2019
- [ ] Registered by: jwikle
- [ ] Clearinghouse URL: http://dmtclearinghouse.esipfed.org/node/10337

Tracking: @karlbenedict @njhoebel

**Comment by njhoebel** [comment]
Reviewed by Raisa too.  Looks good.
