### ISSUE TITLE
Hyku Repository Application

### ISSUE THREAD

**Issue by jwikle** [imls-dmt/resources-workflow#181]
Information about registered data management training resource

- [ ] Date resource added: 02/12/2019
- [ ] Registered by: jwikle
- [ ] Clearinghouse URL: http://dmtclearinghouse.esipfed.org/node/10339

Tracking: @karlbenedict @njhoebel

**Comment by njhoebel** [comment]
Does not meet selection criteria.   Is about a repository platform, but has little to do with RDM per se.
