### ISSUE TITLE
Fedora

### ISSUE THREAD

**Issue by jwikle** [imls-dmt/resources-workflow#182]
Information about registered data management training resource

- [ ] Date resource added: 02/12/2019
- [ ] Registered by: jwikle
- [ ] Clearinghouse URL: http://dmtclearinghouse.esipfed.org/node/10340

Tracking: @karlbenedict @njhoebel

**Comment by njhoebel** [comment]
This resource links to a repository platform, so only indirectly related to RDM.  No downloadable resources are available on RDM topics.  Do not publish and remove from DMTC.
