### ISSUE TITLE
Islandora

### ISSUE THREAD

**Issue by jwikle** [imls-dmt/resources-workflow#183]
Information about registered data management training resource

- [ ] Date resource added: 02/12/2019
- [ ] Registered by: jwikle
- [ ] Clearinghouse URL: http://dmtclearinghouse.esipfed.org/node/10341

Tracking: @karlbenedict @njhoebel

**Comment by njhoebel** [comment]
This resource is not about RDM, but only content management software with no tutorials or downloadable educational resources.  Does not meet selection criteria.  Do not publish and remove from DMTC.
