### ISSUE TITLE
Acquia Drupal Certification Program

### ISSUE THREAD

**Issue by jwikle** [imls-dmt/resources-workflow#185]
Information about registered data management training resource

- [ ] Date resource added: 02/14/2019
- [ ] Registered by: jwikle
- [ ] Clearinghouse URL: http://dmtclearinghouse.esipfed.org/node/10343

Tracking: @karlbenedict @njhoebel

**Comment by njhoebel** [comment]
Does not meet selection criteria.  Is about training certification available for a content management system (Drupal) which is not specifically about RDM.
