### ISSUE TITLE
Top 10 FAIR Data & Software Things

### ISSUE THREAD

**Issue by jwikle** [imls-dmt/resources-workflow#187]
Information about registered data management training resource

- [ ] Date resource added: 02/21/2019
- [ ] Registered by: jwikle
- [ ] Clearinghouse URL: http://dmtclearinghouse.esipfed.org/node/10345

Tracking: @karlbenedict @njhoebel

**Comment by jwikle** [comment]
The resource needs to be updated once the character limit for authors is increased.

**Comment by njhoebel** [comment]
Jacob:  To clarify:  are you wanting to put more authors into the name author group field?  Or, do you need more space for the first and/or last name of a particular author?  If the former, any idea how many more authors would be needed for this record?   Currently, there is an "unlimited" number of values allowed for authors in that group, but there may be a display image.  Would have to investigate with a drupal expert for that, which I can do with the ESIP Drupal expert, or perhaps with the new UNM drupal support staff.  

If we can't solve this quickly, perhaps we could put some names in the contributor field as collaborators?  I'd love to get this resource published for the hackathon this next week, if possible, even if it has to be updated later...

**Comment by jwikle** [comment]
Hi Nancy,

The field for Author needs its character limit increases to allow for more authors. When I tried to add in all of the authors for the resource, at a certain point an error came up saying the limit of 1024 characters was reached. It looks like the limit is based on individual characters, not the number of authors.

If we can double that limit I think we will be safe. The resource is currently missing about 5-10 authors, so I can add them to contributer and update it later once the increase in characters is added.

Jacob Wikle
University of New Mexico
Department of Geography and Environmental Studies
jwikle@unm.edu
USGS New Mexico Water Science Center
jawikle@usgs.gov
505-269-8284

________________________________
