### ISSUE TITLE
Assessing Data Management Needs and Practices to Enable Research Data Support Services

### ISSUE THREAD

**Issue by jwikle** [imls-dmt/resources-workflow#192]
Information about registered data management training resource

- [ ] Date resource added: 02/28/2019
- [ ] Registered by: jwikle
- [ ] Clearinghouse URL: http://dmtclearinghouse.esipfed.org/node/10353

Tracking: @karlbenedict @njhoebel

**Comment by njhoebel** [comment]
Does not meet selection criteria.
