### ISSUE TITLE
ETD+ Toolkit: Training Students to manage ETD+ research outputs

### ISSUE THREAD

**Issue by jwikle** [imls-dmt/resources-workflow#2]
Information about registered data management training resource

- [ ] Date resource added: 08/27/2018
- [ ] Registered by: jwikle
- [ ] Clearinghouse URL: http://dmtclearinghouse.esipfed.org/node/10173

**Comment by njhoebel** [comment]
One more thing:  I also added "Librarian, Educator and Research faculty" to the target audience list per the landing page info.

**Comment by jwikle** [comment]
5: Names are now in descending order per the landing page.
