### ISSUE TITLE
Research Data Management and Open Data

### ISSUE THREAD

**Issue by jwikle** [imls-dmt/resources-workflow#205]
Information about registered data management training resource

- [ ] Date resource added: 03/05/2019
- [ ] Registered by: jwikle
- [ ] Clearinghouse URL: http://dmtclearinghouse.esipfed.org/node/10367

Tracking: @karlbenedict @njhoebel

**Comment by njhoebel** [comment]
1.Changed Publisher to Utrecht University from Figshare.
2.  Added the rest of the FAIR principles to the framework nodes
3.  Added more keywords related to FAIR principles and to data sharing as was specifically mentioned in the slides.
Good resource.
