### ISSUE TITLE
Data Management Planning

### ISSUE THREAD

**Issue by jwikle** [imls-dmt/resources-workflow#206]
Information about registered data management training resource

- [ ] Date resource added: 03/07/2019
- [ ] Registered by: jwikle
- [ ] Clearinghouse URL: http://dmtclearinghouse.esipfed.org/node/10368

Tracking: @karlbenedict @njhoebel

**Comment by njhoebel** [comment]
Does not meet selection criteria:  
 - are fairly static web pages that offer brief instruction and then advertise webinars that are offered only to Utrecht University students, it appears, and are not available independently.
 - seems to be focused upon Utrecht University requirements, so less useful outside.
