### ISSUE TITLE
Data Management Lifecycle and Software Lifecycle Management in the Context of Conducting Science

### ISSUE THREAD

**Issue by jwikle** [imls-dmt/resources-workflow#21]
Information about registered data management training resource

- [ ] Date resource added: 08/27/2018
- [ ] Registered by: jwikle
- [ ] Clearinghouse URL: http://dmtclearinghouse.esipfed.org/node/10154

**Comment by njhoebel** [comment]
This is a paper rather than a downloadable educational resource, albeit a good article. Will put this into the do not publish in order to consider if we change the selection critera.
