### ISSUE TITLE
Open Data Management in Agriculture and Nutrition Online Course

### ISSUE THREAD

**Issue by jwikle** [imls-dmt/resources-workflow#211]
Information about registered data management training resource

- [ ] Date resource added: 03/19/2019
- [ ] Registered by: jwikle
- [ ] Clearinghouse URL: http://dmtclearinghouse.esipfed.org/node/10374

Tracking: @karlbenedict @njhoebel

**Comment by njhoebel** [comment]
Great job, Jacob!  I've moved to publish.
