### ISSUE TITLE
Information Management for Researchers - Good Practice Guides (Oxford)

### ISSUE THREAD

**Issue by jwikle** [imls-dmt/resources-workflow#214]
Information about registered data management training resource

- [ ] Date resource added: 04/04/2019
- [ ] Registered by: jwikle
- [ ] Clearinghouse URL: http://dmtclearinghouse.esipfed.org/node/10379

Tracking: @karlbenedict @njhoebel

**Comment by njhoebel** [comment]
This is more appropriate for the DataONE Skillbuilding hub rather than the DMTC as they don't meet our selection criteria (only downloadable docs).  So, have sent the link on to the DataONE folks and will delete this one from our queue.
