### ISSUE TITLE
Geological Data Management

### ISSUE THREAD

**Issue by jwikle** [imls-dmt/resources-workflow#23]
Information about registered data management training resource

<<<<<<< HEAD
- [ ] Name of resource: Geological Data Management
- [ ] Date resource added: 08/27/2018
- [ ] Registered by: jwikle
- [ ] Clearinghouse URL:  http://dmtclearinghouse.esipfed.org/node/10156

Tracking: @karlbenedict
=======
- [ ] Date resource added: 08/27/2018
- [ ] Registered by: jwikle
- [ ] Clearinghouse URL: http://dmtclearinghouse.esipfed.org/node/10156
>>>>>>> 63dfede6461f1d0e37023e8759d1fb0812800f7e

**Comment by jwikle** [comment]
This one is probably not suitable.

**Comment by njhoebel** [comment]
I agree that this one is not suitable per our existing Selection Guidelines.  If they offered Internet classes more openly, could be considered, but looks like not all products are applicable to RDM anyway.
