### ISSUE TITLE
Developing Data Management Education, Support, and Training

### ISSUE THREAD

**Issue by jwikle** [imls-dmt/resources-workflow#230]
Information about registered data management training resource

- [ ] Date resource added: 04/30/2019
- [ ] Registered by: JWIKLE
- [ ] Clearinghouse URL: http://dmtclearinghouse.esipfed.org/node/10398

Tracking: @karlbenedict @njhoebel

**Comment by njhoebel** [comment]
1.  Added keywords related to the educational aspects of these resources (capacity building, data skills education, etc.)
2.  Added the DOI.
3.  Added the FAIR Data Principle framework with the node of Re-usable data as there was consideration discussion about that topic, it appears.
