### ISSUE TITLE
Data and Software Skills Training for Librarians

### ISSUE THREAD

**Issue by jwikle** [imls-dmt/resources-workflow#234]
Information about registered data management training resource

- [ ] Date resource added: 05/07/2019
- [ ] Registered by: jwikle
- [ ] Clearinghouse URL: http://dmtclearinghouse.esipfed.org/node/10403

Tracking: @karlbenedict @njhoebel

**Comment by njhoebel** [comment]
1.  Added more authors' names
2.  Changed publisher to Library Carpentry from Zenodo which is the repository, not the publisher
3.  Added citation and DOI information.
4.  Added keyword for Capacity building and Data handling.
5.  Changed purpose to Professional Development.
6.  Added target audiences for data supporters, data professional, graduate student, undergraduate student. 
Published and closed issue.
