### ISSUE TITLE
Reproducible Quantitative Methods: Data analysis workflow using R

### ISSUE THREAD

**Issue by jwikle** [imls-dmt/resources-workflow#235]
Information about registered data management training resource

- [ ] Date resource added: 05/09/2019
- [ ] Registered by: jwikle
- [ ] Clearinghouse URL: http://dmtclearinghouse.esipfed.org/node/10404

Tracking: @karlbenedict @njhoebel

**Comment by raisaionin** [comment]
Reviewed, edits made.

**Comment by njhoebel** [comment]
The answer to your question is....
I changed and will move to Publish.

**Comment by njhoebel** [comment]
Used for training with Raisa.  Not reviewed as yet.
