### ISSUE TITLE
Creating a Data Management Plan

### ISSUE THREAD

**Issue by zohrehMehrabi** [imls-dmt/resources-workflow#239]
Information about registered data management training resource

- [ ] Date resource added: 10/16/2019
- [ ] Registered by: 
- [ ] Clearinghouse URL: https://dmtclearinghouse.esipfed.org/node/10428

Tracking: @karlbenedict @njhoebel

**Comment by njhoebel** [comment]
1.  Added author's name (Clara S. Fowler) and authoring organization (Research Medical Library, University of Texas MD Anderson Cancer Center).
2.  Added full names to the acronyms used in the Description.
3.  Changed subject disciplines to Medicine & Health Services, and Medicine & Health Services: Biomedical Science 
4.  Added Standard YouTub License to License field.
5.  Changed Learning Resource Type to Lesson.
