### ISSUE TITLE
Creating Effective Graphs

### ISSUE THREAD

**Issue by zohrehMehrabi** [imls-dmt/resources-workflow#240]
Information about registered data management training resource

- [ ] Date resource added: 10/16/2019
- [ ] Registered by: 
- [ ] Clearinghouse URL: https://dmtclearinghouse.esipfed.org/node/10429

Tracking: @karlbenedict @njhoebel

**Comment by njhoebel** [comment]
Nice job on this one, Zohreh.
I made a couple of changes:
 - in the name of the authoring organization
 - in the name of the publisher.  Let's talk about this.
 - added the Standard YouTube license.
Then, I have a few questions which we can talk about on our call today.

**Comment by zohrehMehrabi** [comment]
I changed the Subject Disciplines to Medicine and Health Sciences, because the speaker use examples related to this field.

**Comment by njhoebel** [comment]
Sounds good.  Moved to publish and closed issue.
