### ISSUE TITLE
Introduction to Python GIS- CSC Training 2018

### ISSUE THREAD

**Issue by zohrehMehrabi** [imls-dmt/resources-workflow#241]
Information about registered data management training resource

- [ ] Date resource added: 10/18/2109
- [ ] Registered by: 
- [ ] Clearinghouse URL: https://dmtclearinghouse.esipfed.org/node/10430

Tracking: @karlbenedict @njhoebel

**Comment by njhoebel** [comment]
1.  Added learning objectives for the course to the Description field.  Removed some information about preparing for the course.
2.  Changed the purpose to "instruction" as this is a full course.
3.  Changed the Learning Resource Type to Course.
4.  Added Grad Student, Undergrad Studt, Early career Scientist, and Data Professional to target audience.
5.  Changed time to more than 1 day, but less than a week as the description stated that the course was scheduled for 3 days (with assignments, presumably).
