### ISSUE TITLE
Earth Lab Free Online Courses, Tutorials and Tools

### ISSUE THREAD

**Issue by zohrehMehrabi** [imls-dmt/resources-workflow#242]
Information about registered data management training resource

- [ ] Date resource added: 10/18/2109
- [ ] Registered by: 
- [ ] Clearinghouse URL: https://dmtclearinghouse.esipfed.org/node/10431

Tracking: @karlbenedict @njhoebel

**Comment by njhoebel** [comment]
The original record was for a textbook at the Earth Lab site, but we have not been adding records for textbooks.  Instead, I broadened the record by changing the title and adding information about the courses, tutorials and tools that are featured at the Earth Lab.  Also, the license information was incorrect, so corrected that.  Good materials though!
