### ISSUE TITLE
UNIX Tutorial for Beginners

### ISSUE THREAD

**Issue by zohrehMehrabi** [imls-dmt/resources-workflow#246]
Information about registered data management training resource

- [ ] Date resource added: 10/18/2109
- [ ] Registered by: 
- [ ] Clearinghouse URL: https://dmtclearinghouse.esipfed.org/node/10435

Tracking: @karlbenedict @njhoebel

**Comment by njhoebel** [comment]
NIce one -- just added an author, authoring organization and publisher based on the (very tiny) link at the bottom of the page.  
Also changed the license (had to add this one to the CV).
