### ISSUE TITLE
Introduction to the Google Earth Engine

### ISSUE THREAD

**Issue by zohrehMehrabi** [imls-dmt/resources-workflow#249]
Information about registered data management training resource

- [ ] Date resource added: 10/21/2109
- [ ] Registered by: 
- [ ] Clearinghouse URL: https://dmtclearinghouse.esipfed.org/node/10439

Tracking: @karlbenedict @njhoebel

**Comment by njhoebel** [comment]
This record is for a guidebook on Google Earth Engine, and so does not fit our selection criteria.
