### ISSUE TITLE
Introduction to R

### ISSUE THREAD

**Issue by jwikle** [imls-dmt/resources-workflow#25]
Information about registered data management training resource

<<<<<<< HEAD
- [ ] Name of resource: Introduction to R
- [ ] Date resource added: 08/27/2018
- [ ] Registered by: jwikle
- [ ] Clearinghouse URL: http://dmtclearinghouse.esipfed.org/node/10159

Tracking: @karlbenedict
=======
- [ ] Date resource added: 08/27/2018
- [ ] Registered by: jwikle
- [ ] Clearinghouse URL: http://dmtclearinghouse.esipfed.org/node/10159
>>>>>>> 63dfede6461f1d0e37023e8759d1fb0812800f7e

**Comment by njhoebel** [comment]
Added name to the author field;  also made DataCamp a publisher.  Added a little more to the description to indicate the "chapter" headings within this resource.  Will move to publish.  Good to get these kinds of resources in the DMTC.
