### ISSUE TITLE
Google Earth Engine Tutorials

### ISSUE THREAD

**Issue by zohrehMehrabi** [imls-dmt/resources-workflow#250]
Information about registered data management training resource

- [ ] Date resource added: 10/21/2109
- [ ] Registered by: 
- [ ] Clearinghouse URL: https://dmtclearinghouse.esipfed.org/node/10440

Tracking: @karlbenedict @njhoebel

**Comment by njhoebel** [comment]
I changed the title of this issue and of this record in the DMTC to be about the Earth Engine Tutorials, generally, and then changed the description to include information about the Community Tutorials as well.  This record can cover most of what fits our selection criteria.  
Looks like a very useful resource.
