### ISSUE TITLE
Steps in a Digital Preservation Workflow

### ISSUE THREAD

**Issue by zohrehMehrabi** [imls-dmt/resources-workflow#255]
Information about registered data management training resource

- [ ] Date resource added: 10/21/2109
- [ ] Registered by: 
- [ ] Clearinghouse URL: https://dmtclearinghouse.esipfed.org/node/10445

Tracking: @karlbenedict @njhoebel

**Comment by njhoebel** [comment]
Nice resource!
Corrected the author / presenter name.
Added librarian to the target audience.
Changed the media type to Presentation.
Added cultural heritage data to the keyword list.
