### ISSUE TITLE
Wordpress.com (hosted) Data Curation Primer

### ISSUE THREAD

**Issue by zohrehMehrabi** [imls-dmt/resources-workflow#256]
Information about registered data management training resource

- [ ] Date resource added: 10/23/2109
- [ ] Registered by: 
- [ ] Clearinghouse URL: https://dmtclearinghouse.esipfed.org/node/10446

Tracking: @karlbenedict @njhoebel

**Comment by njhoebel** [comment]
Changed the URL to the persistent identifier that is part of the citation for the resource, and also mentioned in the descriptive information.
Added "Data Publication" to the keywords.
Added "Librarian" and "Citizen Scientis"t to the Target Audiences.
