### ISSUE TITLE
SPSS Data Curation Primer

### ISSUE THREAD

**Issue by zohrehMehrabi** [imls-dmt/resources-workflow#257]
Information about registered data management training resource

- [ ] Date resource added: 10/23/2109
- [ ] Registered by: 
- [ ] Clearinghouse URL: https://dmtclearinghouse.esipfed.org/node/10447

Tracking: @karlbenedict @njhoebel

**Comment by njhoebel** [comment]
Changed the order of authors to match the list of authors in the citation.  Added information about where other Data Curation Primers could be found.  since the FAIR Data Principles were discussed per the Table of Contents, added the FAIR Data Framework.
