### ISSUE TITLE
Jupyter Notebooks: A Primer for Data Curators

### ISSUE THREAD

**Issue by zohrehMehrabi** [imls-dmt/resources-workflow#258]
Information about registered data management training resource

- [ ] Date resource added: 10/23/2109
- [ ] Registered by: 
- [ ] Clearinghouse URL: https://dmtclearinghouse.esipfed.org/node/10448

Tracking: @karlbenedict @njhoebel

**Comment by njhoebel** [comment]
Changed the URL to be the persistent identifier that was included in the citation and mentioned in the descriptive information on the landing page.
Changed the order of authors to reflect the order in the citation.
Added keywords for "Software management" and "Software preservation".
Added "Early career research scientist", "Librarian" and "High school student" to the target audiences.
