### ISSUE TITLE
Microsoft Excel Data Curation Primer

### ISSUE THREAD

**Issue by zohrehMehrabi** [imls-dmt/resources-workflow#259]
Information about registered data management training resource

- [ ] Date resource added: 10/23/2109
- [ ] Registered by: 
- [ ] Clearinghouse URL: https://dmtclearinghouse.esipfed.org/node/10449

Tracking: @karlbenedict @njhoebel

**Comment by njhoebel** [comment]
Changed the URL to the persistent identifier noted on the landing page.
Changed the order of authors to represent the list as cited.
Added keywords for Data visualization, Organizing data, and Spreadsheets.
Added High school student and Librarian to the target audiences.
