### ISSUE TITLE
American Museum of Natural History Paleoportal Data and Data Management

### ISSUE THREAD

**Issue by jwikle** [imls-dmt/resources-workflow#26]
Information about registered data management training resource

<<<<<<< HEAD
- [ ] Name of resource: American Museum of Natural History Paleoportal Data and Data Management
- [ ] Date resource added: 08/27/2018
- [ ] Registered by: jwikle
- [ ] Clearinghouse URL: http://dmtclearinghouse.esipfed.org/node/10158

Tracking: @karlbenedict
=======
- [ ] Date resource added: 08/27/2018
- [ ] Registered by: jwikle
- [ ] Clearinghouse URL: http://dmtclearinghouse.esipfed.org/node/10158
>>>>>>> 63dfede6461f1d0e37023e8759d1fb0812800f7e

**Comment by njhoebel** [comment]
While useful, this is not a downloadable resource, unfortunately, so will not fit our selection criteria.  Am moving to to Reviewed - Do Not Publish in case the selection criteria change.

**Comment by njhoebel** [comment]
Have saved image of DMTC record in case this is added later, but removed from DMT.
