### ISSUE TITLE
Microsoft Access Data Curation Primer

### ISSUE THREAD

**Issue by zohrehMehrabi** [imls-dmt/resources-workflow#260]
Information about registered data management training resource

- [ ] Date resource added: 10/23/2109
- [ ] Registered by: 
- [ ] Clearinghouse URL: https://dmtclearinghouse.esipfed.org/node/10450

Tracking: @karlbenedict @njhoebel

**Comment by njhoebel** [comment]
Changed URL to the persistent identifier (PID) noted on the landing page.
Added the PID to the identifier field and noted that it was of type "Handle".
Added information about the collection of Data Curation Priemrs.
Added Dave Fearon to the Personal author field.
Added keywords for "database design", "Database management", and "Relational database".
Added Librarian to target audience.
