### ISSUE TITLE
GeoDatabase (.gdb) Data Curation Primer

### ISSUE THREAD

**Issue by zohrehMehrabi** [imls-dmt/resources-workflow#261]
Information about registered data management training resource

- [ ] Date resource added: 10/23/2109
- [ ] Registered by: 
- [ ] Clearinghouse URL: https://dmtclearinghouse.esipfed.org/node/10451

Tracking: @karlbenedict @njhoebel

**Comment by njhoebel** [comment]
Changed URL to the persistent identifier noted on the landing page.
Added information about the full Data Curation primer collection location
Changed the order of authors to match the list in the citation.
Added the PID to the identifier field with type of "Handle".
Added a keyword for "Metadata standards".
Added "Librarian" to the target audience.
