### ISSUE TITLE
Tutorial for using the netCDF Data Curation Primer

### ISSUE THREAD

**Issue by zohrehMehrabi** [imls-dmt/resources-workflow#262]
Information about registered data management training resource

- [ ] Date resource added: 10/23/2109
- [ ] Registered by: 
- [ ] Clearinghouse URL: https://dmtclearinghouse.esipfed.org/node/10452

Tracking: @karlbenedict @njhoebel

**Comment by njhoebel** [comment]
Changed URL to be the PID that was on the landing page.
Added the PID to the identifier field of type Handle.
Added keywords for "Data recipes for Earth science data" and "how-to data recipes".
Changes the Learning Resource Type to "learning activity".
Changed the media type to "Interactive Resource".
