### ISSUE TITLE
Digital Preservation Handbook

### ISSUE THREAD

**Issue by zohrehMehrabi** [imls-dmt/resources-workflow#264]
Information about registered data management training resource

- [ ] Date resource added: 
- [ ] Registered by: 
- [ ] Clearinghouse URL: https://dmtclearinghouse.esipfed.org/node/10454

Tracking: @karlbenedict @njhoebel

**Comment by njhoebel** [comment]
Discussed this with Zohreh.  This looks like a good resource for the following reasons:
1.  Subject is quite pertinent.
2.  There are a number of downloadable resources within the text itself despite the fact that it is a more or less static web page resource.
3.  The authors are well known & respected in the field. 
4.  Lots of good information.
No information to add;  well done, Zohreh!
Move to publish. Will keep as edge case for instructional purposes.
