### ISSUE TITLE
Persistent Identifiers: Current Features and Future Properties (Webinar)

### ISSUE THREAD

**Issue by zohrehMehrabi** [imls-dmt/resources-workflow#265]
Information about registered data management training resource

- [ ] Date resource added: 10/25/2109
- [ ] Registered by: 
- [ ] Clearinghouse URL: https://dmtclearinghouse.esipfed.org/node/10455

Tracking: @karlbenedict @njhoebel

**Comment by njhoebel** [comment]
Changed media type to "Presentation".  Otherwise, looks good!
