### ISSUE TITLE
ANDS Guides to Persistent identifiers: working level

### ISSUE THREAD

**Issue by zohrehMehrabi** [imls-dmt/resources-workflow#268]
Information about registered data management training resource

- [ ] Date resource added: 10/25/2109
- [ ] Registered by: 
- [ ] Clearinghouse URL: https://dmtclearinghouse.esipfed.org/node/10458

Tracking: @karlbenedict @njhoebel

**Comment by njhoebel** [comment]
Edited the title a bit to make it easier to find the entire series of guides on this topic.
Added info to the description mentioning the other, existing guides.
Added "data discovery and identification", "data citation" "data management" and "data policy" to keywords.
Added "librarian" to target audience.
Added FAIR DAta Principles to the Educational Framework with nodes for findable, interoperable and accessible.
