### ISSUE TITLE
DOIs to support citation of grey literature - PiDs Short bites

### ISSUE THREAD

**Issue by zohrehMehrabi** [imls-dmt/resources-workflow#269]
Information about registered data management training resource

- [ ] Date resource added: 10/25/2109
- [ ] Registered by: 
- [ ] Clearinghouse URL: https://dmtclearinghouse.esipfed.org/node/10459

Tracking: @karlbenedict @njhoebel

**Comment by njhoebel** [comment]
Added information about the whole series of webinars in description.
Added a key word for "grey literature".
Added "librarian" to target audience.  
Changed publisher to ARDC.
