### ISSUE TITLE
Intro to Python for Data Science

### ISSUE THREAD

**Issue by jwikle** [imls-dmt/resources-workflow#27]
Information about registered data management training resource

- [ ] Date resource added: 08/27/2018
- [ ] Registered by: jwikle
- [ ] Clearinghouse URL: http://dmtclearinghouse.esipfed.org/node/10160

Tracking: @karlbenedict

**Comment by njhoebel** [comment]
Another good one.  Just added:
1.   a little more text to the description including what was covered in the chapters.  
2.  Also, added "data sharing" and "Interoperable data - FAIR data principle" to the keyword list.
3.  Added SW engineer and data professional to the target audiences.  
Moved to publish.
