### ISSUE TITLE
Linking data and publications - the Scholix initiative -PiDs short bites

### ISSUE THREAD

**Issue by zohrehMehrabi** [imls-dmt/resources-workflow#271]
Information about registered data management training resource

- [ ] Date resource added: 10/25/2109
- [ ] Registered by: 
- [ ] Clearinghouse URL: https://dmtclearinghouse.esipfed.org/node/10461

Tracking: @karlbenedict @njhoebel

**Comment by njhoebel** [comment]
Changed title to add capital letters to all pertinent words.
Added "Digital scholarship" to keywords.
Added two contributors (person and organization)
Changed publisher to ARDC.
Added Librarian to target audience.
