### ISSUE TITLE
RAID, a PiD for projects- PiDs Short Bites

### ISSUE THREAD

**Issue by zohrehMehrabi** [imls-dmt/resources-workflow#272]
Information about registered data management training resource

- [ ] Date resource added: 10/25/2109
- [ ] Registered by: 
- [ ] Clearinghouse URL: https://dmtclearinghouse.esipfed.org/node/10462

Tracking: @karlbenedict @njhoebel

**Comment by njhoebel** [comment]
Changed the order of the authors to reflect the order of presentation in the webinar.
Added two contributors (person and organization).
Changed publisher to ARDC.
