### ISSUE TITLE
20 Years of Persistent Identifiers – Which Systems are Here to Stay?

### ISSUE THREAD

**Issue by zohrehMehrabi** [imls-dmt/resources-workflow#274]
Information about registered data management training resource

- [ ] Date resource added: 
- [ ] Registered by: 
- [ ] Clearinghouse URL: https://dmtclearinghouse.esipfed.org/node/10464

Tracking: @karlbenedict @njhoebel

**Comment by njhoebel** [comment]
No downloadable videos or other tutorial-like resources within;  a good article, but only an article nevertheless.  Will not publish, but keep as an edge case.
