### ISSUE TITLE
PID Platform

### ISSUE THREAD

**Issue by zohrehMehrabi** [imls-dmt/resources-workflow#275]
Information about registered data management training resource

- [ ] Date resource added: 10/25/2109
- [ ] Registered by: 
- [ ] Clearinghouse URL: https://dmtclearinghouse.esipfed.org/node/10465

Tracking: @karlbenedict @njhoebel

**Comment by karlbenedict** [comment]
This is a test comment

**Comment by karlbenedict** [comment]
this is another test comment

**Comment by karlbenedict** [comment]
another test comment

**Comment by njhoebel** [comment]
Added some contextual information regarding the Project source in the description.
Added Funding organization as a Target Audience.
Excellent resource!
