### ISSUE TITLE
Big Data Hadoop Tutorial for Beginners: Learn in 7 Days!

### ISSUE THREAD

**Issue by zohrehMehrabi** [imls-dmt/resources-workflow#279]
Information about registered data management training resource

- [ ] Date resource added: 10/30/2109
- [ ] Registered by: 
- [ ] Clearinghouse URL: https://dmtclearinghouse.esipfed.org/node/10470

Tracking: @karlbenedict @njhoebel

**Comment by njhoebel** [comment]
Just added a note to the description noting the existence of ads on the pages.  
Added subject disciplines for Engineering:  computer engineering and Physical Sciences and Mathematics:  Computer Sciences.
