### ISSUE TITLE
Intermediate R

### ISSUE THREAD

**Issue by jwikle** [imls-dmt/resources-workflow#28]
Information about registered data management training resource

- [ ] Date resource added: 08/27/2018
- [ ] Registered by: jwikle
- [ ] Clearinghouse URL: http://dmtclearinghouse.esipfed.org/node/10162

Tracking: @karlbenedict

**Comment by njhoebel** [comment]
Just added SW Engineer and Data professional to the target audience list.  
Moved to Publish.
