### ISSUE TITLE
SEEK: a systems biology data and model management platform

### ISSUE THREAD

**Issue by zohrehMehrabi** [imls-dmt/resources-workflow#282]
Information about registered data management training resource

- [ ] Date resource added: 10/30/2109
- [ ] Registered by: 
- [ ] Clearinghouse URL: https://dmtclearinghouse.esipfed.org/node/10473

Tracking: @karlbenedict @njhoebel

**Comment by zohrehMehrabi** [comment]
It is not a Tutorial, it is just a paper about SEEK  a platform for Biology.

**Comment by njhoebel** [comment]
Right, as such, it doesn't fit our selection criteria, so I am going to delete it from the DMTC.  Looks like a good article though....
