### ISSUE TITLE
An Introduction to Humanities Data Curation

### ISSUE THREAD

**Issue by zohrehMehrabi** [imls-dmt/resources-workflow#283]
Information about registered data management training resource

- [ ] Date resource added: 11/01/2019
- [ ] Registered by: 
- [ ] Clearinghouse URL:  https://dmtclearinghouse.esipfed.org/node/10474

Tracking: @karlbenedict @njhoebel

**Comment by njhoebel** [comment]
Added contributors for the funding organizations found on the About page.
