### ISSUE TITLE
Data management in the arts and humanities

### ISSUE THREAD

**Issue by zohrehMehrabi** [imls-dmt/resources-workflow#284]
Information about registered data management training resource

- [ ] Date resource added: 11/01/2019
- [ ] Registered by: 
- [ ] Clearinghouse URL:  https://dmtclearinghouse.esipfed.org/node/10475

Tracking: @karlbenedict @njhoebel

**Comment by njhoebel** [comment]
Changed licensing information to be Creative Commons CC BY.
Added full name (finally found it!) to the contributor field.
Added Librarian to target audience.
