### ISSUE TITLE
Efficient BIM Data Management & Quality Control of Revit Projects

### ISSUE THREAD

**Issue by zohrehMehrabi** [imls-dmt/resources-workflow#285]
Information about registered data management training resource

- [ ] Date resource added: 11/01/2019
- [ ] Registered by: 
- [ ] Clearinghouse URL: https://dmtclearinghouse.esipfed.org/node/10476

Tracking: @karlbenedict @njhoebel

**Comment by zohrehMehrabi** [comment]
I am wondering this kind of tutorial is useful for DMTC material?

**Comment by njhoebel** [comment]
Upon consultation with Karl & others;  agree that this should be included in the DMTC inventory.
Added some pertinent keywords for BIM and Revit data format.
