### ISSUE TITLE
Data Management for Small Design Teams - SOLIDWORKS Enterprise PDM

### ISSUE THREAD

**Issue by zohrehMehrabi** [imls-dmt/resources-workflow#286]
Information about registered data management training resource

- [ ] Date resource added: 11/01/2019
- [ ] Registered by: 
- [ ] Clearinghouse URL: https://dmtclearinghouse.esipfed.org/node/10477

Tracking: @karlbenedict @njhoebel

**Comment by zohrehMehrabi** [comment]
I am wondering this kind of tutorial is useful for DMTC material?

**Comment by njhoebel** [comment]
This one seems much more of a sales tutorial than some of the others that you've had a question about.  Also, because it was created in 2015, the software itself will probably have changed.  I say this one is not appropriate, so will delete it from the DMTC.
