### ISSUE TITLE
Top 5 Workflows for Precise BIM Data Management

### ISSUE THREAD

**Issue by zohrehMehrabi** [imls-dmt/resources-workflow#287]
Information about registered data management training resource

- [ ] Date resource added: 11/01/2019
- [ ] Registered by: 
- [ ] Clearinghouse URL: https://dmtclearinghouse.esipfed.org/node/10478

Tracking: @karlbenedict @njhoebel

**Comment by zohrehMehrabi** [comment]
I am wondering this kind of tutorial is useful for DMTC material?

**Comment by njhoebel** [comment]
This tutorial does talk about how to make data fit standards and other RDM issues, and while it is about a particular software product, it appears to be more about RDM than the product.  Will move to publish.
Added keywords for BIM and Revit models.
