### ISSUE TITLE
Geoscience Data Management Overview: Geoscience Librarianship 101

### ISSUE THREAD

**Issue by jwikle** [imls-dmt/resources-workflow#29]
Information about registered data management training resource

- [ ] Date resource added: 08/27/2018
- [ ] Registered by: jwikle
- [ ] Clearinghouse URL: http://dmtclearinghouse.esipfed.org/node/10163

Tracking: @karlbenedict

**Comment by karlbenedict** [comment]
adding @njhoebel

**Comment by jwikle** [comment]
Static Page

**Comment by njhoebel** [comment]
Agree this should be removed;  does not seem to be a live link anymore either.  Have deleted from the DMTC.
