### ISSUE TITLE
THE PARTHENOS E-HUMANITIES AND E-HERITAGE WEBINAR SERIES

### ISSUE THREAD

**Issue by zohrehMehrabi** [imls-dmt/resources-workflow#297]
Information about registered data management training resource

- [ ] Date resource added: 11/04/2019
- [ ] Registered by: 
- [ ] Clearinghouse URL: https://dmtclearinghouse.esipfed.org/node/10489

Tracking: @karlbenedict @njhoebel

**Comment by njhoebel** [comment]
Added the names of the authors listed in the credits, and the universities mentioned to the authors fields
Added PARTHENOS as a contributor
Added an explanation of where to find the slides and video recordings of the webinar to the description.
Changed the form of the title from all caps to our usual format of capital letters for major words.
