### ISSUE TITLE
Temporal Network Analysis with R

### ISSUE THREAD

**Issue by zohrehMehrabi** [imls-dmt/resources-workflow#298]
Information about registered data management training resource

- [ ] Date resource added: 11/08/2019
- [ ] Registered by: 
- [ ] Clearinghouse URL: https://dmtclearinghouse.esipfed.org/node/10490

Tracking: @karlbenedict @njhoebel

**Comment by njhoebel** [comment]
Added prerequisites to the description
Added The Programming Historian to the Authoring Organization name
changed the citation to include the DOI (had been updated)
Added DOI to the identifier field & DOI to the ID type field.
Added Humanities data, Network analysis, and Digital humanities to the keywords.
changed the Purpose to Instruction
Changed Learning Resource Type to "learning activity."  
Good resource!
