### ISSUE TITLE
Analyzing Documents with TF-IDF

### ISSUE THREAD

**Issue by zohrehMehrabi** [imls-dmt/resources-workflow#299]
Information about registered data management training resource

- [ ] Date resource added: 11/08/2019
- [ ] Registered by: 
- [ ] Clearinghouse URL: https://dmtclearinghouse.esipfed.org/node/10491

Tracking: @karlbenedict @njhoebel

**Comment by njhoebel** [comment]
Added prerequisites (suggested prior skills ) to description
Added The Programming Historian to the Authoring Org Name
Updated the citation
Added the DOI to the ID field and DOI to the ID Type field.
Added humanities data, natural language processing and digital humanities to the keywords.
Changed the purpose to instruction.
Changed the learning resource type to "learning activity'.

These are excellent resources, it seems!
