### ISSUE TITLE
Visualizing Data with Bokeh and Pandas

### ISSUE THREAD

**Issue by zohrehMehrabi** [imls-dmt/resources-workflow#300]
Information about registered data management training resource

- [ ] Date resource added: 11/08/2019
- [ ] Registered by: 
- [ ] Clearinghouse URL: https://dmtclearinghouse.esipfed.org/node/10492

Tracking: @karlbenedict @njhoebel

**Comment by njhoebel** [comment]
Another nice one from this author / group.  
Have just added the name of the dataset to the description.  All else looks good!
