### ISSUE TITLE
Introduction to the Principles of Linked Open Data

### ISSUE THREAD

**Issue by zohrehMehrabi** [imls-dmt/resources-workflow#303]
Information about registered data management training resource

- [ ] Date resource added: 11/08/2019
- [ ] Registered by: 
- [ ] Clearinghouse URL: https://dmtclearinghouse.esipfed.org/node/10495

Tracking: @karlbenedict @njhoebel

**Comment by njhoebel** [comment]
This is a good one, Zohreh.  I see there is a Spanish version.  Would you please add a record to the DMTC in Spanish where possible?  Might as well make it available if they've gone to the trouble of creating it in two languages.  Thanks!

I've published the English language version.

**Comment by zohrehMehrabi** [comment]
I added the Spanish version.
