### ISSUE TITLE
From Hermeneutics to Data to Networks: Data Extraction and Network Visualization of Historical Sources

### ISSUE THREAD

**Issue by zohrehMehrabi** [imls-dmt/resources-workflow#304]
Information about registered data management training resource

- [ ] Date resource added: 11/08/2019
- [ ] Registered by: 
- [ ] Clearinghouse URL: https://dmtclearinghouse.esipfed.org/node/10496

Tracking: @karlbenedict @njhoebel

**Comment by njhoebel** [comment]
I added the list of topics to the description that was available from the resource.

This also is available in Spanish, so ask that you add a record for the Spanish version as well, please.
