### ISSUE TITLE
Centre of Excellence Ocean Data Management

### ISSUE THREAD

**Issue by zohrehMehrabi** [imls-dmt/resources-workflow#305]
Information about registered data management training resource

- [ ] Date resource added: 11/11/2019
- [ ] Registered by: 
- [ ] Clearinghouse URL: https://dmtclearinghouse.esipfed.org/node/10497

Tracking: @karlbenedict @njhoebel

**Comment by njhoebel** [comment]
Added a statement to the description about needing either a guest login or organizational membership.

Also added Citizen Scientist to the Target audience list.
