### ISSUE TITLE
IOCCP & BONUS INTEGRAL Training Course on "Instrumenting our oceans for better observation: a training course on a suite of biogeochemical sensors"

### ISSUE THREAD

**Issue by zohrehMehrabi** [imls-dmt/resources-workflow#306]
Information about registered data management training resource

- [ ] Date resource added: 11/11/2019
- [ ] Registered by: 
- [ ] Clearinghouse URL: https://dmtclearinghouse.esipfed.org/node/10498

Tracking: @karlbenedict @njhoebel

**Comment by njhoebel** [comment]
Added keyword for biogeochemical data.  
Added a little more info to the description about the course sponsors and about the expectations for the course.
