### ISSUE TITLE
Ocean Data Management for Researchers

### ISSUE THREAD

**Issue by zohrehMehrabi** [imls-dmt/resources-workflow#308]
Information about registered data management training resource

- [ ] Date resource added: 11/11/2019
- [ ] Registered by: 
- [ ] Clearinghouse URL: https://dmtclearinghouse.esipfed.org/node/10500

Tracking: @karlbenedict @njhoebel

**Comment by njhoebel** [comment]
Added the trust fund organization to the Organizations controlled vocabulary list and to this record.  Should also be added to other Ocean Teacher courses in future.  I will add to the previous one on Ocean Data Mangement.
