### ISSUE TITLE
Health and Medical Short Bites #1 - Funders and publishers

### ISSUE THREAD

**Issue by zohrehMehrabi** [imls-dmt/resources-workflow#312]
Information about registered data management training resource

- [ ] Date resource added: 11/13/2019
- [ ] Registered by: 
- [ ] Clearinghouse URL: https://dmtclearinghouse.esipfed.org/node/10504

Tracking: @karlbenedict @njhoebel

**Comment by njhoebel** [comment]
Since transcripts are available for these webinars, I added "Accessibility Features - Structure and Navigation" to this record.
I also added Keywords for Scholarly publishing and Scientific publications since that was a topic area for one of the instructors for this part of the webinar series.
