### ISSUE TITLE
Health and Medical Short Bites #2 - Storing and publishing health and medical data

### ISSUE THREAD

**Issue by zohrehMehrabi** [imls-dmt/resources-workflow#313]
Information about registered data management training resource

- [ ] Date resource added: 11/13/2019
- [ ] Registered by: 
- [ ] Clearinghouse URL: https://dmtclearinghouse.esipfed.org/node/10505

Tracking: @karlbenedict @njhoebel

**Comment by njhoebel** [comment]
Added Accessibility information to this record too as it has transcripts available.  Will add them to all the records for this series (assuming they all have transcripts.)
