### ISSUE TITLE
Health & Medical Data Short Bites #4 - Patient views on data sharing 

### ISSUE THREAD

**Issue by zohrehMehrabi** [imls-dmt/resources-workflow#315]
Information about registered data management training resource

- [ ] Date resource added: 11/13/2019
- [ ] Registered by: 
- [ ] Clearinghouse URL: https://dmtclearinghouse.esipfed.org/node/10507

Tracking: @karlbenedict @njhoebel

**Comment by njhoebel** [comment]
Added keywords for "data use restrictions", "informed consent", and "data privacy".
