### ISSUE TITLE
Health & Medical Data Short Bites #5 - Data linkage and the Australian Health Thesaurus

### ISSUE THREAD

**Issue by zohrehMehrabi** [imls-dmt/resources-workflow#316]
Information about registered data management training resource

- [ ] Date resource added: 11/13/2019
- [ ] Registered by: 
- [ ] Clearinghouse URL: https://dmtclearinghouse.esipfed.org/node/10508

Tracking: @karlbenedict @njhoebel

**Comment by njhoebel** [comment]
Added keywords (new) for "data linkage" and "probabilistic data linkage".  Deleted the keywords for "text and data mining" and "linked data" as those have different, specific meanings that don't seem to related to the topics covered in this webinar, and for this subject discipline.
