### ISSUE TITLE
How to Make a Data Dictionary

### ISSUE THREAD

**Issue by jwikle** [imls-dmt/resources-workflow#32]
Information about registered data management training resource

- [ ] Date resource added: 08/30/2018
- [ ] Registered by: jwikle
- [ ] Clearinghouse URL: http://dmtclearinghouse.esipfed.org/node/10100

Tracking: @karlbenedict @njhoebel

**Comment by njhoebel** [comment]
This _could_ possibly be published as a learning activity although there are no exercises with it as it's just a static web page.  Have added the "add to FAQ" tag as an example to use for documentation and/or for consideration during the evaluation of the Selection Criteria activities.
I have changed the Media type to text and the Learning Resource type to Learning activity.  
I have also added this to the  FAIR framework with the step for "Re-usability".

**Comment by njhoebel** [comment]
Based on discussions at ESIP winter 2019 regarding the accommodation of different learning styles, have published this resource to the DMTC.  Is still useful as an example for documentation via the FAQ, and as an example of the need for additions to either the learning resource type or to the media type.
