### ISSUE TITLE
Big data applications: Real-world strategies for managing big data

### ISSUE THREAD

**Issue by zohrehMehrabi** [imls-dmt/resources-workflow#323]
Information about registered data management training resource

- [ ] Date resource added: 11/20/2019
- [ ] Registered by: 
- [ ] Clearinghouse URL: https://dmtclearinghouse.esipfed.org/node/10516

Tracking: @karlbenedict @njhoebel

**Comment by njhoebel** [comment]
This is a blog entry for a company, so out of scope for the DMTC.
