### ISSUE TITLE
An introduction to individual patient data meta-analysis using the Vivli platform

### ISSUE THREAD

**Issue by zohrehMehrabi** [imls-dmt/resources-workflow#325]
Information about registered data management training resource

- [ ] Date resource added: 11/22/2019
- [ ] Registered by: 
- [ ] Clearinghouse URL: https://dmtclearinghouse.esipfed.org/node/10518

Tracking: @karlbenedict @njhoebel

**Comment by njhoebel** [comment]
Out of scope;  not about RDM.
