### ISSUE TITLE
REGARD 3D Tutorials 

### ISSUE THREAD

**Issue by jwikle** [imls-dmt/resources-workflow#33]
Information about registered data management training resource

- [ ] Date resource added: 08/30/2018
- [ ] Registered by:  jwikle
- [ ] Clearinghouse URL: http://dmtclearinghouse.esipfed.org/node/10124

Tracking: @karlbenedict @njhoebel

**Comment by jwikle** [comment]
In hindsight, this resource may not be an appropriate addition to the database.

**Comment by njhoebel** [comment]
Yes, I'd have to agree.  Would be useful as a skill to have certainly (and I'm going to send the link to friends who may be interested to know how to do this!), but not about data management skill development.
