### ISSUE TITLE
Getting Started with Topic Modeling and MALLET

### ISSUE THREAD

**Issue by zohrehMehrabi** [imls-dmt/resources-workflow#333]
Information about registered data management training resource

- [ ] Date resource added: 11/27/2019
- [ ] Registered by: 
- [ ] Clearinghouse URL: https://dmtclearinghouse.esipfed.org/node/10528

Tracking: @karlbenedict @njhoebel

**Comment by njhoebel** [comment]
Also added a Spanish version at https://dmtclearinghouse.esipfed.org/node/11242
