### ISSUE TITLE
QGIS - for Absolute Beginners

### ISSUE THREAD

**Issue by jwikle** [imls-dmt/resources-workflow#34]
Information about registered data management training resource

- [ ] Date resource added: 08/30/2018
- [ ] Registered by: jwikle
- [ ] Clearinghouse URL:  http://dmtclearinghouse.esipfed.org/node/10121

Tracking: @karlbenedict @njhoebel

**Comment by njhoebel** [comment]
1.  Added keywords for cyberinfrastructure for science, data visualization and transformation tools, and data handling.
2.  Added software engineer to target audience.
