### ISSUE TITLE
Yield Monitor Data Post-Processing or "Cleaning"

### ISSUE THREAD

**Issue by zohrehMehrabi** [imls-dmt/resources-workflow#340]
Information about registered data management training resource

- [ ] Date resource added: 12/4/2019
- [ ] Registered by: 
- [ ] Clearinghouse URL: https://dmtclearinghouse.esipfed.org/node/10536

Tracking: @karlbenedict @njhoebel

**Comment by njhoebel** [comment]
Title changed when updated in 2022.
