### ISSUE TITLE
Describe software through metadata-Making data accessible-Provenance and workflows and Making software executable by others

### ISSUE THREAD

**Issue by zohrehMehrabi** [imls-dmt/resources-workflow#345]
Information about registered data management training resource

- [ ] Date resource added: 12/09/2019
- [ ] Registered by: 
- [ ] Clearinghouse URL: https://dmtclearinghouse.esipfed.org/node/10543

Tracking: @karlbenedict @njhoebel

**Comment by njhoebel** [comment]
This portal is no longer active and the presentation slides linked from the portal were presented in 2015;  there have been other resources on these topics that are more recent and complete.
