### ISSUE TITLE
Essentials of Geographic Information Systems

### ISSUE THREAD

**Issue by jwikle** [imls-dmt/resources-workflow#35]
Information about registered data management training resource

- [ ] Date resource added: 08/30/2018
- [ ] Registered by: jwikle
- [ ] Clearinghouse URL: http://dmtclearinghouse.esipfed.org/node/10119

Tracking: @karlbenedict @njhoebel

**Comment by njhoebel** [comment]
Is a chapter from a book;  does not fit the selection criteria.

**Comment by njhoebel** [comment]
Hold this as an edge case for consideration by an Editorial Board.
