### ISSUE TITLE
Tabular model at the 1400 compatibility level

### ISSUE THREAD

**Issue by zohrehMehrabi** [imls-dmt/resources-workflow#351]
Information about registered data management training resource

- [ ] Date resource added: 12/13/2019
- [ ] Registered by: 
- [ ] Clearinghouse URL: https://dmtclearinghouse.esipfed.org/node/10550

Tracking: @karlbenedict @njhoebel

**Comment by njhoebel** [comment]
This resource is no longer current as Microsoft has discontinued the service which the tutorial references.
