### ISSUE TITLE
Data Mining Tutorials (Analysis Services)

### ISSUE THREAD

**Issue by zohrehMehrabi** [imls-dmt/resources-workflow#352]
Information about registered data management training resource

- [ ] Date resource added: 12/13/2019
- [ ] Registered by: 
- [ ] Clearinghouse URL: https://dmtclearinghouse.esipfed.org/node/10551

Tracking: @karlbenedict @njhoebel

**Comment by zohrehMehrabi** [comment]
I suggest adding Machin learning key words to this tutorial.

**Comment by njhoebel** [comment]
This resource is no longer viable due to the discontinuation of the Microsoft service it references.
