### ISSUE TITLE
Copyright, credit, scooping: the tricky details of protocol-sharing

### ISSUE THREAD

**Issue by zohrehMehrabi** [imls-dmt/resources-workflow#358]
Information about registered data management training resource

- [ ] Date resource added: 12/18/2019
- [ ] Registered by: 
- [ ] Clearinghouse URL: https://dmtclearinghouse.esipfed.org/node/10559

Tracking: @karlbenedict @njhoebel

**Comment by njhoebel** [comment]
This resource is no longer available
