### ISSUE TITLE
 Learn how to use protocols.io as part of publishing research papers

### ISSUE THREAD

**Issue by zohrehMehrabi** [imls-dmt/resources-workflow#361]
Information about registered data management training resource

- [ ] Date resource added: 12/18/2019
- [ ] Registered by: 
- [ ] Clearinghouse URL: https://dmtclearinghouse.esipfed.org/node/10562

Tracking: @karlbenedict @njhoebel

**Comment by njhoebel** [comment]
This resource is no longer available.
