### ISSUE TITLE
Historical research: Databases for research in History and Archaeology

### ISSUE THREAD

**Issue by zohrehMehrabi** [imls-dmt/resources-workflow#366]
Information about registered data management training resource

- [ ] Date resource added: 12/20/2019
- [ ] Registered by: 
- [ ] Clearinghouse URL: https://dmtclearinghouse.esipfed.org/node/10567

Tracking: @karlbenedict @njhoebel

**Comment by njhoebel** [comment]
The link in the record does not resolve and a search for the course does not resolve to anything, so appears to be out of date.
