### ISSUE TITLE
module 1: Introduction to research data

### ISSUE THREAD

**Issue by zohrehMehrabi** [imls-dmt/resources-workflow#367]
Information about registered data management training resource

- [ ] Date resource added: 12/20/2019
- [ ] Registered by: 
- [ ] Clearinghouse URL: https://dmtclearinghouse.esipfed.org/node/10568

Tracking: @karlbenedict @njhoebel

**Comment by zohrehMehrabi** [comment]
this tutorial is a part of the MANTRA Research Data Management Training which exists in clearinghouses. first I searched the title and it did not show anything so I added it but today I found that there is a page for all MANTRA Research Data Management Training.

**Comment by njhoebel** [comment]
OK, will do.  Thanks!
