### ISSUE TITLE
Visual Arts Data Skills for Researchers Workshop

### ISSUE THREAD

**Issue by zohrehMehrabi** [imls-dmt/resources-workflow#368]
Information about registered data management training resource

- [ ] Date resource added: 
- [ ] Registered by: 
- [ ] Clearinghouse URL: https://dmtclearinghouse.esipfed.org/node/10569

Tracking: @karlbenedict @njhoebel

**Comment by njhoebel** [comment]
These presentations referenced at this resource are no longer available.
