### ISSUE TITLE
Writing a data management plan

### ISSUE THREAD

**Issue by zohrehMehrabi** [imls-dmt/resources-workflow#372]
Information about registered data management training resource

- [ ] Date resource added: 
- [ ] Registered by: 
- [ ] Clearinghouse URL: https://dmtclearinghouse.esipfed.org/node/10573

Tracking: @karlbenedict @njhoebel

**Comment by njhoebel** [comment]
This resource is quite out of date at this point;  refers to policies that have changed & other, more current resources are available for this basic topic.
