### ISSUE TITLE
EPA Environmental Data Management in Support of Sharing Data and Management

### ISSUE THREAD

**Issue by jwikle** [imls-dmt/resources-workflow#38]
Information about registered data management training resource

- [ ] Date resource added: 08/30/2018
- [ ] Registered by: jwikle
- [ ] Clearinghouse URL: http://dmtclearinghouse.esipfed.org/node/10113

Tracking: @karlbenedict @njhoebel

**Comment by jwikle** [comment]
Static page.

**Comment by njhoebel** [comment]
Agree that this doesn't meet the Selection Criteria.
