### ISSUE TITLE
Python for Data Science

### ISSUE THREAD

**Issue by zohrehMehrabi** [imls-dmt/resources-workflow#389]
Information about registered data management training resource

- [ ] Date resource added: 1/17/2020
- [ ] Registered by: 
- [ ] Clearinghouse URL: https://dmtclearinghouse.esipfed.org/node/10591

Tracking: @karlbenedict @njhoebel

**Comment by njhoebel** [comment]
Title had changed a bit, but still viable.  Move to publish
