### ISSUE TITLE
Genomics Workshop

### ISSUE THREAD

**Issue by jwikle** [imls-dmt/resources-workflow#41]
Information about registered data management training resource

- [ ] Date resource added: 09/06/2018
- [ ] Registered by: jwikle
- [ ] Clearinghouse URL: http://dmtclearinghouse.esipfed.org/node/10104

Tracking: @karlbenedict @njhoebel

**Comment by njhoebel** [comment]
Very exciting resource:  had a citation and a doi!  (K know, I'm easily pleased!)
1.  Added a little bit to the description which described the prior experience needed, and the fact that a dataset was recommended to be used.
2.  Added keyword for "genomics data" which may not have been in the CV when this was record was first created.
3.  Changed the  intended time to complete to be more than 1 day, but less than a week as the description on the website stated that the workshop was intended to be done over 2 days.
4.  Changed the media type to "Interactive Resource".
5.  Changed the learning resource type to "Unit" as it is one of many topics covered by Data Carpentry and on a particular type of data.
Moved to Publish.
