### ISSUE TITLE
What Should Your Data Management Plan Address?

### ISSUE THREAD

**Issue by jwikle** [imls-dmt/resources-workflow#42]
Information about registered data management training resource

- [ ] Date resource added: 09/06/2018
- [ ] Registered by: jwikle 
- [ ] Clearinghouse URL: http://dmtclearinghouse.esipfed.org/node/10114

Tracking: @karlbenedict @njhoebel

**Comment by njhoebel** [comment]
I'd say that this resource is too generic, and not unique enough as a guide to include in the inventory, so will move to Reviewed, do not publish.  Have added an "edge case" label in case the EB wants to reconsider in future.
