### ISSUE TITLE
Why should you worry about good data management practices?

### ISSUE THREAD

**Issue by jwikle** [imls-dmt/resources-workflow#43]
Information about registered data management training resource

- [ ] Date resource added: 09/06/2018
- [ ] Registered by: jwikle
- [ ] Clearinghouse URL: http://dmtclearinghouse.esipfed.org/node/10116

Tracking: @karlbenedict @njhoebel

**Comment by njhoebel** [comment]
1.  Added more info in description about the broader areas covered in this resource (e.g., Data management plans).
2.  Added subject disciplines for areas of focus for ORNL DAAC (biogeochemical and ecological data and models -- or as close as I could come to these).
Moved to publish
