### ISSUE TITLE
Best Practices for Successful GIS Data Management

### ISSUE THREAD

**Issue by jwikle** [imls-dmt/resources-workflow#44]
Information about registered data management training resource

- [ ] Date resource added: 09/06/2018
- [ ] Registered by: jwikle
- [ ] Clearinghouse URL: http://dmtclearinghouse.esipfed.org/node/10118

Tracking: @karlbenedict @njhoebel

**Comment by njhoebel** [comment]
Not enough here to keep in the inventory, I think, especially as a static web page.  Will move to remove.
