### ISSUE TITLE
QGIS Training Manual

### ISSUE THREAD

**Issue by jwikle** [imls-dmt/resources-workflow#45]
Information about registered data management training resource

- [ ] Date resource added: 09/06/2018
- [ ] Registered by: jwikle
- [ ] Clearinghouse URL: http://dmtclearinghouse.esipfed.org/node/10120

Tracking: @karlbenedict @njhoebel

**Comment by njhoebel** [comment]
1.  Added more specific information in the description field about what is included in the manual and about QGIS more generally.
2.  Added keywords about the various kinds of tools:  visualization, DM and transformation tools as well as data handling, and data visualization.
3.  Added physical science disciplines for Earth and Environmental sciences to subject discipline.
