### ISSUE TITLE
Data Management Resources (University of Arizona Research Data Management Services)

### ISSUE THREAD

**Issue by jwikle** [imls-dmt/resources-workflow#46]
Information about registered data management training resource

- [ ] Date resource added: 09/06/2018
- [ ] Registered by: jwikle
- [ ] Clearinghouse URL: http://dmtclearinghouse.esipfed.org/node/10111

Tracking: @karlbenedict @njhoebel

**Comment by njhoebel** [comment]
1.  Have changed this resource into the broader title of "Data Management Resources" as there are a number of pages below that level which seem to provide important information.  
2.  Added information in the description about the broader topics covered including workshops and tutorials.
3.  Changed the authoring organization to be the University of Arizona Libraries.
4.  Added keywords for data management planning & data sharing.
5.  Changed the learning resource type to course given how much was being covered by this overall website.
Have moved to publish.
