### ISSUE TITLE
Smithsonian Libraries: Describing Your Project : Citation Metadata

### ISSUE THREAD

**Issue by jwikle** [imls-dmt/resources-workflow#47]
Information about registered data management training resource

- [ ] Date resource added: 09/06/2018
- [ ] Registered by: jwikle
- [ ] Clearinghouse URL: http://dmtclearinghouse.esipfed.org/node/10109

Tracking: @karlbenedict @njhoebel

**Comment by njhoebel** [comment]
Same as the previous Smithsonian Best Practice.  Have sent on to DataONE. 

Have not yet deleted from DMTC.

**Comment by njhoebel** [comment]
Per discussions at ESIP winter 2019, have published this resource (argument was that the imagery with the dog pictures was a unique and memorable way to describe the concepts of good citation metadata.  Should still be considered an edge case for further discussion by ED Brd.

**Comment by njhoebel** [comment]
Have added keywords for data discovery, data citation, data sharing and discovery metadata.
