### ISSUE TITLE
Smithsonian Data Management Best Practices 

### ISSUE THREAD

**Issue by jwikle** [imls-dmt/resources-workflow#48]
Information about registered data management training resource

- [ ] Date resource added: 09/06/2018
- [ ] Registered by: jwikle
- [ ] Clearinghouse URL: http://dmtclearinghouse.esipfed.org/node/10108

Tracking: @karlbenedict @njhoebel

**Comment by njhoebel** [comment]
This doesn't fit the Selection Criteria for an educational resource, but I will send on for DataONE to consider including in their Best Practices store on the Data Skillbuilding Hub.

**Comment by njhoebel** [comment]
Have saved an image of the DMTC record in case it's needed, but removed from DMTC.  Has been sent to DataONE.
