### ISSUE TITLE
Data Carpentry Geospatial Workshop

### ISSUE THREAD

**Issue by jwikle** [imls-dmt/resources-workflow#49]
Information about registered data management training resource

- [ ] Date resource added: 09/06/2018
- [ ] Registered by: jwikle
- [ ] Clearinghouse URL: http://dmtclearinghouse.esipfed.org/node/10105

Tracking: @karlbenedict @njhoebel

**Comment by njhoebel** [comment]
1.  Added more description to clarify what was included in the workshop and how it relates to data management skill / capacity building.
2. Added keywords to give a sense of how the use of R could be translated into different activities in the data lifecycle.
3. Added an Education for Science subject discipline.
Move to Publish.  Glad to get this into the Clearinghouse!
