### ISSUE TITLE
GIS Best Practices: Managing GIS

### ISSUE THREAD

**Issue by jwikle** [imls-dmt/resources-workflow#51]
Information about registered data management training resource

- [ ] Date resource added: 09/06/2018
- [ ] Registered by: jwikle
- [ ] Clearinghouse URL: http://dmtclearinghouse.esipfed.org/node/10185

Tracking: @karlbenedict @njhoebel

**Comment by jwikle** [comment]
Static PDF page

**Comment by njhoebel** [comment]
Agreed.  Sending this to folks at the DataONE Skillbuilding Hub Best Practice section.
