### ISSUE TITLE
Python for Data Management

### ISSUE THREAD

**Issue by jwikle** [imls-dmt/resources-workflow#53]
Information about registered data management training resource

- [ ] Date resource added: 09/10/2018
- [ ] Registered by: jawikle
- [ ] Clearinghouse URL: http://dmtclearinghouse.esipfed.org/node/10188

Tracking: @karlbenedict @njhoebel

**Comment by njhoebel** [comment]
1. Added a keyword for Python
2.  Added subject disciplines for Physical Sciences:  Earth Sciences & Environmental Sciences
3.  Added contributor of type collaborator for the person who "modified" the course
4.  Added this resource to the USGS Science Support Framework with nodes of Describe / Metadata and Publish / Share.
