### ISSUE TITLE
Atlas.ti Data Curation Primer

### ISSUE THREAD

**Issue by zohrehMehrabi** [imls-dmt/resources-workflow#538]
Information about registered data management training resource

- [ ] Date resource added: 8/12/2020
- [ ] Registered by: 
- [ ] Clearinghouse URL: https://dmtclearinghouse.esipfed.org/node/10862

Tracking: @karlbenedict @njhoebel

**Comment by njhoebel** [comment]
Added a keyword for "Qualitative data analysis" to the controlled vocabulary list.
Changed contributor Dave Fearon to contributor type for "mentoring" 
Changed contributor Hannah Hadley to contributor type for "collaborator".
Added "data professional" to target audience and deleted "undergraduate student".
