### ISSUE TITLE
Guidelines for Effective Data Management Plans

### ISSUE THREAD

**Issue by jwikle** [imls-dmt/resources-workflow#54]
Information about registered data management training resource

- [ ] Date resource added: 09/10/2018
- [ ] Registered by: jawikle
- [ ] Clearinghouse URL: http://dmtclearinghouse.esipfed.org/node/10189

Tracking: @karlbenedict @njhoebel

**Comment by njhoebel** [comment]
1. Changed the Author organization to ICPSR, leaving the publisher the same per the Citation mentioned on the landing page.
2.  Added the Citation that was suggested on the landing page.
3.  Published
