### ISSUE TITLE
How-to Guides to Managing a Research Project

### ISSUE THREAD

**Issue by jwikle** [imls-dmt/resources-workflow#56]
Information about registered data management training resource

- [ ] Date resource added: 09/10/2018
- [ ] Registered by: jawikle
- [ ] Clearinghouse URL: http://dmtclearinghouse.esipfed.org/node/10191

Tracking: @karlbenedict @njhoebel

**Comment by njhoebel** [comment]
Changed this record to refer to the more unique How-to Guides offered by this organization as they are general, but also cover different, more specific topics than the page originally identified, as follows:
1.  Changed title and URL 
2.  Changed description to include the range of topics covered by the how-to guides.
3.  Changed the authoring organization to the UCL Library Services,  but kept the publisher as UCL.
4.  Added keywords to cover more of the topics covered in the guides.
