### ISSUE TITLE
SAR for Landcover Applications

### ISSUE THREAD

**Issue by zohrehMehrabi** [imls-dmt/resources-workflow#562]
Information about registered data management training resource

- [ ] Date resource added: 9/16/2020
- [ ] Registered by: 
- [ ] Clearinghouse URL: https://dmtclearinghouse.esipfed.org/node/10943

Tracking: @karlbenedict @njhoebel

**Comment by njhoebel** [comment]
Added some keywords for this resource including synthetic aperture radar (SAR), soil moisture analysis, remote sensing, and landcover applications.  Will add to the Spanish version as well.

Otherwise, looks good.  Will have the NASA reviewer look at this too.
