### ISSUE TITLE
Remote Sensing for Freshwater Habitats

### ISSUE THREAD

**Issue by zohrehMehrabi** [imls-dmt/resources-workflow#564]
Information about registered data management training resource

- [ ] Date resource added: 9/16/2020
- [ ] Registered by: 
- [ ] Clearinghouse URL: https://dmtclearinghouse.esipfed.org/node/10945

Tracking: @karlbenedict @njhoebel

**Comment by njhoebel** [comment]
Added a new keyword for "freshwater habitat applications", also added "environmental change records" as a keyword.
Added Contact name of Brock Blevins which is the same for all of these webinars.
