### ISSUE TITLE
SAR for Disasters and Hydrological Applications

### ISSUE THREAD

**Issue by zohrehMehrabi** [imls-dmt/resources-workflow#565]
Information about registered data management training resource

- [ ] Date resource added: 9/17/2020
- [ ] Registered by: 
- [ ] Clearinghouse URL: https://dmtclearinghouse.esipfed.org/node/10946

Tracking: @karlbenedict @njhoebel

**Comment by njhoebel** [comment]
Added Brock Blevins as Contact person.
Added keywords for flood mapping applications, remote sensing, and SAR
Deleted keywords for Lidar technology and software management.
