### ISSUE TITLE
Using the UN Biodiversity Lab to Support National Conservation and Sustainable Development Goals

### ISSUE THREAD

**Issue by zohrehMehrabi** [imls-dmt/resources-workflow#567]
Information about registered data management training resource

- [ ] Date resource added: 9/17/2020
- [ ] Registered by: 
- [ ] Clearinghouse URL: https://dmtclearinghouse.esipfed.org/node/10948

Tracking: @karlbenedict @njhoebel

**Comment by njhoebel** [comment]
Added Brock Blevins as contact person.
Added contributors for the main convening partners (UNDP, UNEP, GEF, and CBD).
Added keywords for remote sensing and a new one for Aichi Biodiversity Targets (ABTs).
Will add the same info to the Spanish and French versions.

**Comment by zohrehMehrabi** [comment]
I will do that.
