### ISSUE TITLE
Utilizando el UN Biodiversity Lab para Apoyar los Objetivos Nacionales de Conservación y Desarrollo Sostenible

### ISSUE THREAD

**Issue by zohrehMehrabi** [imls-dmt/resources-workflow#569]
Information about registered data management training resource

- [ ] Date resource added: 9/17/2020
- [ ] Registered by: 
- [ ] Clearinghouse URL: https://dmtclearinghouse.esipfed.org/node/10950

Tracking: @karlbenedict @njhoebel

**Comment by njhoebel** [comment]
Made same changes as with the other two versions.
Would you also add the Spanish names for the contributors to this record as with the French version.  See the French version issue for more specifics.  Let me know if you have questions.  THANKS!!!!  Won't publish the Spanish and French records until they're complete.

**Comment by zohrehMehrabi** [comment]
I added the Spanish form of organization.
