### ISSUE TITLE
Satellite Remote Sensing for Agricultural Applications

### ISSUE THREAD

**Issue by zohrehMehrabi** [imls-dmt/resources-workflow#570]
Information about registered data management training resource

- [ ] Date resource added: 9/17/2020
- [ ] Registered by: 
- [ ] Clearinghouse URL: https://dmtclearinghouse.esipfed.org/node/10951

Tracking: @karlbenedict @njhoebel

**Comment by njhoebel** [comment]
Added keywords for remote sensing, new keywords (kw) for drought monitoring, crop monitoring, soil moisture applications  and agriculture applications.
Deleted keywords for SDGs, and sustainable cities.
