### ISSUE TITLE
Forest Mapping and Monitoring with SAR Data

### ISSUE THREAD

**Issue by zohrehMehrabi** [imls-dmt/resources-workflow#571]
Information about registered data management training resource

- [ ] Date resource added: 9/18/2020
- [ ] Registered by: 
- [ ] Clearinghouse URL: https://dmtclearinghouse.esipfed.org/node/10953

Tracking: @karlbenedict @njhoebel

**Comment by njhoebel** [comment]
Added Brock Blevins as Contact person.
Added keywords for forest mapping applications, landcover applications, remote sensing.
