### ISSUE TITLE
Mapeo y Monitoreo de los Bosques con Datos SAR

### ISSUE THREAD

**Issue by zohrehMehrabi** [imls-dmt/resources-workflow#572]
Information about registered data management training resource

- [ ] Date resource added: 9/18/2020
- [ ] Registered by: 
- [ ] Clearinghouse URL: https://dmtclearinghouse.esipfed.org/node/10954

Tracking: @karlbenedict @njhoebel

**Comment by njhoebel** [comment]
Added Brock Blevins as contact person.
Added keywords for forest mapping applications, landcover applications, environmental change records, remote sensing and SAR.
