### ISSUE TITLE
Groundwater Monitoring using Observations from NASA’s Gravity Recovery and Climate Experiment (GRACE) Missions

### ISSUE THREAD

**Issue by zohrehMehrabi** [imls-dmt/resources-workflow#573]
Information about registered data management training resource

- [ ] Date resource added: 9/23/2020
- [ ] Registered by: 
- [ ] Clearinghouse URL: https://dmtclearinghouse.esipfed.org/node/10960

Tracking: @karlbenedict @njhoebel

**Comment by njhoebel** [comment]
Added keywords for "drought monitoring" and a new keyword for "groundwater monitoring".
