### ISSUE TITLE
Understanding Phenology with Remote Sensing

### ISSUE THREAD

**Issue by zohrehMehrabi** [imls-dmt/resources-workflow#574]
Information about registered data management training resource

- [ ] Date resource added: 9/23/2020
- [ ] Registered by: 
- [ ] Clearinghouse URL: https://dmtclearinghouse.esipfed.org/node/10961

Tracking: @karlbenedict @njhoebel

**Comment by njhoebel** [comment]
Added keyword to the controlled vocabulary list for "ecological processes" and then to this record.
