### ISSUE TITLE
Using Earth Observations to Monitor Water Budgets for River Basin Management II

### ISSUE THREAD

**Issue by zohrehMehrabi** [imls-dmt/resources-workflow#575]
Information about registered data management training resource

- [ ] Date resource added: 9/23/2020
- [ ] Registered by: 
- [ ] Clearinghouse URL: https://dmtclearinghouse.esipfed.org/node/10962

Tracking: @karlbenedict @njhoebel

**Comment by njhoebel** [comment]
Added new keywords to the CV list and to this record for:  "Water quality" and "River basin management".
