### ISSUE TITLE
Remote Sensing of Coastal Ecosystems

### ISSUE THREAD

**Issue by zohrehMehrabi** [imls-dmt/resources-workflow#576]
Information about registered data management training resource

- [ ] Date resource added:9/24/2020 
- [ ] Registered by: 
- [ ] Clearinghouse URL: https://dmtclearinghouse.esipfed.org/node/10963

Tracking: @karlbenedict @njhoebel

**Comment by njhoebel** [comment]
Added "Undergraduate student" and "Graduate student" to the target audience given the foundational nature of this training.
