### ISSUE TITLE
Teledetección de Ecosistemas Costeros

### ISSUE THREAD

**Issue by zohrehMehrabi** [imls-dmt/resources-workflow#577]
Information about registered data management training resource

- [ ] Date resource added: 9/24/2020
- [ ] Registered by: 
- [ ] Clearinghouse URL: https://dmtclearinghouse.esipfed.org/node/10964

Tracking: @karlbenedict @njhoebel

**Comment by njhoebel** [comment]
Added "Undergraduate student" and "Data professional" to the targeted audience and deleted "Data manager".
