### ISSUE TITLE
Columbia Research Data Management Tutorials and Templates

### ISSUE THREAD

**Issue by jwikle** [imls-dmt/resources-workflow#58]
Information about registered data management training resource

- [ ] Date resource added: 09/10/2018
- [ ] Registered by: jawikle
- [ ] Clearinghouse URL: http://dmtclearinghouse.esipfed.org/node/10193

Tracking: @karlbenedict @njhoebel

**Comment by njhoebel** [comment]
The URL is no longer valid for this resource;  however, a related page on the same web site includes a number of useful tutorials, so I am changing the record to reflect a change in title, etc.,  as follows:
1.  Columbia Research Data Management Tutorials and Templates.
2.  Changed the description including reference to the sponsoring program
3.  Added author name and organization
4.  Added keywords related to tools, notebooks and physical samples per the description of the resources referenced from the page.
5.  Changed the Purpose of the resource to instruction from professional development.
