### ISSUE TITLE
Fundamentals of Remote Sensing

### ISSUE THREAD

**Issue by zohrehMehrabi** [imls-dmt/resources-workflow#581]
Information about registered data management training resource

- [ ] Date resource added: 10/2/2020
- [ ] Registered by: 
- [ ] Clearinghouse URL: https://dmtclearinghouse.esipfed.org/node/10975

Tracking: @karlbenedict @njhoebel

**Comment by njhoebel** [comment]
Since this is a foundational training, I added "Undergraduate student" and "Graduate student" to the target audience.
