### ISSUE TITLE
An Inside Look at how NASA Measures Air Pollution [Introductory]

### ISSUE THREAD

**Issue by zohrehMehrabi** [imls-dmt/resources-workflow#585]
Information about registered data management training resource

- [ ] Date resource added: 10/8/2020
- [ ] Registered by: 
- [ ] Clearinghouse URL: https://dmtclearinghouse.esipfed.org/node/10982

Tracking: @karlbenedict @njhoebel

**Comment by zohrehMehrabi** [comment]
Maybe air pollution monitoring/air quality/ Image interpretation would be good keywords to add.

**Comment by njhoebel** [comment]
Good idea;  I added "Air quality data" to the keyword list & to this record.  "Air pollution" should be picked up in the title and description fields.
I also added "Data professional", "Graduate student", "Undergraduate student", and "Educator" to the target audience (figuring that journalists could be considered "educators").
