### ISSUE TITLE
Un Vistazo a Cómo la NASA Mide la Contaminación del Aire [Introductorio]

### ISSUE THREAD

**Issue by zohrehMehrabi** [imls-dmt/resources-workflow#586]
Information about registered data management training resource

- [ ] Date resource added: 10/8/2020
- [ ] Registered by: 
- [ ] Clearinghouse URL: https://dmtclearinghouse.esipfed.org/node/10983

Tracking: @karlbenedict @njhoebel

**Comment by njhoebel** [comment]
I added "Air quality data" to the keyword list & to this record. 
I also added "Data professional", "Graduate student", "Undergraduate student", and "Educator" to the target audience (figuring that journalists could be considered "educators").
