### ISSUE TITLE
Data Management Plan - Data Management Guides

### ISSUE THREAD

**Issue by jwikle** [imls-dmt/resources-workflow#59]
Information about registered data management training resource

- [ ] Date resource added: 09/10/2018
- [ ] Registered by: jawikle 
- [ ] Clearinghouse URL: http://dmtclearinghouse.esipfed.org/node/10194

Tracking: @karlbenedict @njhoebel

**Comment by njhoebel** [comment]
Generally, this is a static page, but given the breadth of the coverage, it's worth publishing, I think.  I think it's an edge case.

To the description, added a link to the Courses and Tutorials page.
