### ISSUE TITLE
Earth Observations for Disaster Risk Assessment & Resilience[Introductory]

### ISSUE THREAD

**Issue by zohrehMehrabi** [imls-dmt/resources-workflow#590]
Information about registered data management training resource

- [ ] Date resource added: 10/14/2020
- [ ] Registered by: 
- [ ] Clearinghouse URL: https://dmtclearinghouse.esipfed.org/node/10992

Tracking: @karlbenedict @njhoebel

**Comment by zohrehMehrabi** [comment]
suggested keyword:
Earth observation (EO) data

**Comment by njhoebel** [comment]
Good ideas;  Added "Earth observation data", "Climate risk assessment applications", and "Climate resilience" to the CV list.
Added Undergraduate student, Graduate student, Data professional, and Educator to the target audience since this is a foundational training resource.
