### ISSUE TITLE
Remote Sensing for Conservation & Biodiversity [Introductory]

### ISSUE THREAD

**Issue by zohrehMehrabi** [imls-dmt/resources-workflow#598]
Information about registered data management training resource

- [ ] Date resource added: 10/15/2020
- [ ] Registered by: 
- [ ] Clearinghouse URL: https://dmtclearinghouse.esipfed.org/node/11001

Tracking: @karlbenedict @njhoebel

**Comment by njhoebel** [comment]
Changed Learning resource type to "Lesson" rather than "Interactive resource" -- unlike some of the other ARSET resources, this one did not seem to have interaction involved to my eye.
Added Data professional, undergrad, grad student & educator to the target audience list.

**Comment by njhoebel** [comment]
Also, added a sentence in the description explaining that the presentation materials are available in English and Spanish, but there is no explanatory landing page in Spanish for this resource.  Could be confusing to see that it's also available in Spanish, but not be able to find a record in Spanish.  Hope that helps those searchers!
