### ISSUE TITLE
Earth Science Metadata Standards

### ISSUE THREAD

**Issue by jwikle** [imls-dmt/resources-workflow#6]
Information about registered data management training resource

- [ ] Date resource added: 08/27/2018
- [ ] Registered by: jwikle
- [ ] Clearinghouse URL: http://dmtclearinghouse.esipfed.org/node/10177

**Comment by njhoebel** [comment]
In case we add this resource in future, here's the URL:  http://www.dcc.ac.uk/resources/subject-areas/earth-science .  Have saved the DMTC record as an image, but removed from the DMTC.
