### ISSUE TITLE
Create a Data Management Plan

### ISSUE THREAD

**Issue by jwikle** [imls-dmt/resources-workflow#60]
Information about registered data management training resource

- [ ] Date resource added: 09/10/2018
- [ ] Registered by: jawikle
- [ ] Clearinghouse URL: http://dmtclearinghouse.esipfed.org/node/10195

Tracking: @karlbenedict @njhoebel

**Comment by njhoebel** [comment]
This resource is a static page that does not seem to be especially unique or comprehensive, so marking it as an edge case and moving to do not publish.
