### ISSUE TITLE
Good DMP Examples + Going Beyond Two Pages

### ISSUE THREAD

**Issue by jwikle** [imls-dmt/resources-workflow#61]
Information about registered data management training resource

- [ ] Date resource added: 09/10/2018
- [ ] Registered by: jawikle
- [ ] Clearinghouse URL: http://dmtclearinghouse.esipfed.org/node/10196

Tracking: @karlbenedict @njhoebel

**Comment by njhoebel** [comment]
Dated (from 2012) and very basic, static page with references to resources already included in the inventory.  Will remove from the DMTC.
