### ISSUE TITLE
Data Services: Introduction to Data Management

### ISSUE THREAD

**Issue by jwikle** [imls-dmt/resources-workflow#63]
Information about registered data management training resource

- [ ] Date resource added: 09/10/2018
- [ ] Registered by: jawikle
- [ ] Clearinghouse URL: http://dmtclearinghouse.esipfed.org/node/10198

Tracking: @karlbenedict @njhoebel

**Comment by raisaionin** [comment]
The resource no longer exists. Needs to be removed from the Clearinghouse.
