### ISSUE TITLE
Engaging Researchers in Good Data Management

### ISSUE THREAD

**Issue by zohrehMehrabi** [imls-dmt/resources-workflow#658]
Information about registered data management training resource

- [ ] Date resource added: 2/5/2021
- [ ] Registered by: 
- [ ] Clearinghouse URL: https://dmtclearinghouse.esipfed.org/node/11152

Tracking: @karlbenedict @njhoebel

**Comment by njhoebel** [comment]
Poor recording and out of date at this point.  Will not publish.
