### ISSUE TITLE
Managing and Sharing Qualitative Research Data 101

### ISSUE THREAD

**Issue by jwikle** [imls-dmt/resources-workflow#7]
Information about registered data management training resource

- [ ] Date resource added: 08/27/2018
- [ ] Registered by: jwikle 
- [ ] Clearinghouse URL: http://dmtclearinghouse.esipfed.org/node/10176

**Comment by jwikle** [comment]
This is a single web page, and may be removed if not suitable.

**Comment by njhoebel** [comment]
This is a static web page that has no downloadable resources associated with it.  Does not meet the current selection criteria.
