### ISSUE TITLE
Python: Working with Multidimensional Scientific Data

### ISSUE THREAD

**Issue by jwikle** [imls-dmt/resources-workflow#71]
Information about registered data management training resource

- [ ] Date resource added: 09/17/2018
- [ ] Registered by: jawikle 
- [ ] Clearinghouse URL: http://dmtclearinghouse.esipfed.org/node/10206

Tracking: @karlbenedict @njhoebel

**Comment by raisaionin** [comment]
added: 
-ArcGIS to the list of keyword and to the resource keywords
-Purpose - Professional development
-Time to complete - up to 1 hour
-Media type - Presentation
-Learning Resource type - Learning activity

**Comment by njhoebel** [comment]
Added keywords for data analysis, data visualization, data sharing, and a new keyword for multidimensional data (scientific).  
Otherwise, looked good.  Moving to publish.
