### ISSUE TITLE
RDMRose Learning Materials

### ISSUE THREAD

**Issue by jwikle** [imls-dmt/resources-workflow#73]
Information about registered data management training resource

- [ ] Date resource added: 09/17/2018
- [ ] Registered by: jawikle
- [ ] Clearinghouse URL: http://dmtclearinghouse.esipfed.org/node/10208

Tracking: @karlbenedict @njhoebel

**Comment by njhoebel** [comment]
This is a duplicate of http://dmtclearinghouse.esipfed.org/node/10302
