### ISSUE TITLE
Do-It-Yourself Research Data Management Training Kit for Librarians

### ISSUE THREAD

**Issue by jwikle** [imls-dmt/resources-workflow#74]
Information about registered data management training resource

- [ ] Date resource added: 09/17/2018
- [ ] Registered by: jawikle
- [ ] Clearinghouse URL: http://dmtclearinghouse.esipfed.org/node/10209

Tracking: @karlbenedict @njhoebel

**Comment by njhoebel** [comment]
This is a duplicate of http://dmtclearinghouse.esipfed.org/node/9897, so will be deleted.
