### ISSUE TITLE
TraD: Training for Data management at UEL

### ISSUE THREAD

**Issue by jwikle** [imls-dmt/resources-workflow#81]
Information about registered data management training resource

- [ ] Date resource added: Updated 09/20/2018
- [ ] Registered by: Nancy Hoebelheinrich
- [ ] Clearinghouse URL: http://dmtclearinghouse.esipfed.org/node/10056

Tracking: @karlbenedict @njhoebel

**Comment by njhoebel** [comment]
This resource is no longer available except by visiting a legal deposit library in the UK.  Withdrawing from our queues.
