### ISSUE TITLE
Rethinking Research Data | Kristin Briney | TEDxUWMilwaukee

### ISSUE THREAD

**Issue by jwikle** [imls-dmt/resources-workflow#82]
Information about registered data management training resource

- [ ] Date resource added: 09/24/2018
- [ ] Registered by: jwikle
- [ ] Clearinghouse URL: http://dmtclearinghouse.esipfed.org/node/10218

Tracking: @karlbenedict @njhoebel

**Comment by raisaionin** [comment]
added:

License - standard youtube license
Purpose - None
Time to complete - less than 1 hour
Media type  - moving image
Learning resource type - None

**Comment by njhoebel** [comment]
Changed learning resource type to lesson.
Added keyword:  "Scientific reproducibility".
Moved to publish
