### ISSUE TITLE
CMU Database Systems - 01 Course introduction & Relational Data Model (Fall 2018)

### ISSUE THREAD

**Issue by jwikle** [imls-dmt/resources-workflow#84]
Information about registered data management training resource

- [ ] Date resource added: 09/24/2018
- [ ] Registered by: jwikle
- [ ] Clearinghouse URL: http://dmtclearinghouse.esipfed.org/node/10220

Tracking: @karlbenedict @njhoebel

**Comment by raisaionin** [comment]
added:
License - standard youtube lisence
Keyword - SQL (also added to the taxonomy)
                  Indexing (also added to the taxonomy))
Purpose: instruction
Time to complete - more than 1 day
Learning resource type  - course
Media type -

**Comment by njhoebel** [comment]
Looks good.  Moved to publish.
