### ISSUE TITLE
Introduction to Geospatial Data Management

### ISSUE THREAD

**Issue by jwikle** [imls-dmt/resources-workflow#91]
Information about registered data management training resource

- [ ] Date resource added: updated 09/27/2018
- [ ] Registered by: jwikle
- [ ] Clearinghouse URL: http://dmtclearinghouse.esipfed.org/node/10117

Tracking: @karlbenedict @njhoebel

**Comment by raisaionin** [comment]
Added: 

Contributor Organization(s) - Dataversity. (Added Dataversity as a new organization)
Keywords: Big Data, Data Governance, Data Modeling, Data Quality, Metadata,

**Comment by njhoebel** [comment]
Doesn't meet our selection criteria;  an article, not a learning resource in our sense of the word.
