### ISSUE TITLE
Think Python

### ISSUE THREAD

**Issue by jwikle** [imls-dmt/resources-workflow#92]
Information about registered data management training resource

- [ ] Date resource added: 09/27/2018
- [ ] Registered by: jwikle
- [ ] Clearinghouse URL: http://dmtclearinghouse.esipfed.org/node/10227

Tracking: @karlbenedict @njhoebel

**Comment by raisaionin** [comment]
Added: 

1. One small additional paragraph to the Description: "Some examples and exercises are based on Swampy, a Python package written by the author to demonstrate aspects of software design, and to give readers a chance to experiment with simple graphics and animation."

2. Citation, Chicago style: Downey, Allen B. Think Python: Sebastopol, CA: OReilly, 2012.

3. Time to complete: More than 1 week

**Comment by njhoebel** [comment]
This does not meet our selection criteria;  it's essentially an ad for a book.  It's a useful book, probably, but not a learning resource per se.  
Moving to Reviewed;  do not publish and deleting from the DMTC.
