### ISSUE TITLE
Learning programming on Khan Academy

### ISSUE THREAD

**Issue by jwikle** [imls-dmt/resources-workflow#94]
Information about registered data management training resource

- [ ] Date resource added: 09/27/2018
- [ ] Registered by: jwikle
- [ ] Clearinghouse URL: http://dmtclearinghouse.esipfed.org/node/10229

Tracking: @karlbenedict @njhoebel

**Comment by raisaionin** [comment]
Tried to add "JavaScript" keyword. Keyword has been added to the DTMC, but I am unable to add it to the record - it does not come up.

**Comment by raisaionin** [comment]
Target audience - added "Middle school student"
Purpose - added "instruction"
Time to complete - more than 1 hour, but less than a day
Media type - Put "Animation", but it could also be "Presentation"
Learning resourced type - Put "Learning Activity"

**Comment by njhoebel** [comment]
1.  Changed media type to "interactive resource".
2.  Changed license to MIT License.
3.  Added link in Usage Rights Information to the Khan Academy Terms of Service.
Looks like a nice resource!
