### ISSUE TITLE
Linux for Biologists

### ISSUE THREAD

**Issue by jwikle** [imls-dmt/resources-workflow#95]
Information about registered data management training resource

- [ ] Date resource added: 09/27/2018 
- [ ] Registered by: jwikle
- [ ] Clearinghouse URL: http://dmtclearinghouse.esipfed.org/node/10230

Tracking: @karlbenedict @njhoebel

**Comment by raisaionin** [comment]
added keywords: biology, linux, unix

license: left undeclared

Published / Broadcast Date: changed from 09/26/2010 to 09/26/2018

Target Audience: added "Mid-career research scientist"

Purpose: added "instruction"

time to complete: more than a day, but less than a week

Media type: presentation

Learning Resource Type: Learning Activity

**Comment by njhoebel** [comment]
Good additions.
Changed the authoring organization to be "Institute of Biotechnology, Cornell University", but kept the publisher as "Cornell University."
