### ISSUE TITLE
2018 NOAA Environmental Data Management Workshop (EDMW)

### ISSUE THREAD

**Issue by jwikle** [imls-dmt/resources-workflow#96]
Information about registered data management training resource

- [ ] Date resource added: 10/01/2018
- [ ] Registered by: jwikle
- [ ] Clearinghouse URL: http://dmtclearinghouse.esipfed.org/node/10231

Tracking: @karlbenedict @njhoebel

**Comment by raisaionin** [comment]
Added keywords: metadata, metadata editors, metadata registries, metadata standards, data archiving, scientific record archives, scientific publications

**Comment by raisaionin** [comment]
Publisher/broadcast date and Created date is 04/27/2018
Did not find it in the record, but I am going to leave it as is.

**Comment by raisaionin** [comment]
added purpose: Professional development
time to competed: put More then 1 day, but less than 1 week
media type: presentation
learning resource type: Primary source

**Comment by njhoebel** [comment]
Good resource!
Added more info in the description about key topic areas, then added keywords that represented some of those topic ideas.
Added FAIR Data Principles Framework & Nodes for Accessibility & Findability
Added Librarian to target audience.
Changed media type to "Collection" as both slides & recordings are available.
