### ISSUE TITLE
Data management for postdocs and research scientists

### ISSUE THREAD

**Issue by jwikle** [imls-dmt/resources-workflow#97]
Information about registered data management training resource

- [ ] Date resource added: 10/01/2018
- [ ] Registered by: jwikle
- [ ] Clearinghouse URL: http://dmtclearinghouse.esipfed.org/node/10232

Tracking: @karlbenedict @njhoebel

**Comment by njhoebel** [comment]
No longer available at the URL given;  can't find elsewhere either.  Will remove from DMTC.
