### ISSUE TITLE
Quick & dirty data management: the 5 things you should absolutely be doing with your data now

### ISSUE THREAD

**Issue by jwikle** [imls-dmt/resources-workflow#98]
Information about registered data management training resource

- [ ] Date resource added: 10/01/2018
- [ ] Registered by: jwikle
- [ ] Clearinghouse URL: http://dmtclearinghouse.esipfed.org/node/10233

Tracking: @karlbenedict @njhoebel

**Comment by jwikle** [comment]
This is a drop box file, so it could be considered as static.

**Comment by njhoebel** [comment]
This is not a particularly unique presentation, and is very MIT-centric, so will not publish;  Will remove from the DMTC.
